### ISSUE TITLE
[Bug]: Auto width of table columns doesn't work

### ISSUE THREAD

**Issue by Skarema** [lowcoder-org/lowcoder#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/lowcoder-org/lowcoder/assets/84594421/df77e1ff-580a-4459-b267-65bfc454f402)

### Expected Behavior

adjust width automatically

### Steps to reproduce

set column to auto width (at least tag and button columns don't work)

### Environment

Version: 2.4.1

**Comment by FalkWolsky** [comment]
This will be solved in v2.4.2 (today)

**Comment by adnanqaops** [comment]
This issue is fixed. Done and Deployed to Prod. So, closing out this issue.
