### ISSUE TITLE
[Bug]: Select component is not showing multiple values in the dropdown

### ISSUE THREAD

**Issue by adnanqaops** [lowcoder-org/lowcoder#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The **Select** component is not showing multiple values in the dropdown, even though I have multiple values in the data of **Select** component. It only shows first value. 
Please check this video : https://www.loom.com/share/874bf4e1d10c448393a2bb82714688ee?sid=6180337c-4510-4ec4-8fa8-45d3c498122d

### Expected Behavior

The **Select** component should show all the values given in the Data.

### Steps to reproduce

Issue has been explained in the Video here : https://www.loom.com/share/874bf4e1d10c448393a2bb82714688ee?sid=6180337c-4510-4ec4-8fa8-45d3c498122d
App link : https://app.lowcoder.cloud/apps/667eb219f0558f2f43e386c3/edit

### Environment

Production --> V2.4.1

**Comment by raheeliftikhar5** [comment]
This is because value is not assigned. After assigning the value, it works fine.
