### ISSUE TITLE
[Bug]: Query -Timeout After- Behavior

### ISSUE THREAD

**Issue by MichalisDBA** [lowcoder-org/lowcoder#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello.

If you setup a MSSQL query and try to increase the `Timeout After` in `Advanced` tab, although you have increased `LOWCODER_MAX_QUERY_TIMEOUT` in `.env`, it does not work.

![image](https://github.com/lowcoder-org/lowcoder/assets/68512501/42d976a3-3a1c-417b-83c9-4f7c8e42cbf2)

If you then try to run a simple query that it takes 3 minutes to complete, you get an error in 2 minutes mark.

`query1 run failed: {"code":"QUERY_EXECUTION_ERROR","message":"Request Timeout"}`

### Expected Behavior

Increase actually the `Timeout After` value beyond `120s` when you configure the appropriate `.env` variable

### Steps to reproduce

Set `LOWCODER_MAX_QUERY_TIMEOUT: 3600` env variable.

Create a simple app with a Microsoft SQL data source.

Go to `Advanced` tab and set the `Timeout After` to 3600s or anything beyond 120s.

For the query to run and simulate a 3 minute delay write this:

```
WAITFOR DELAY '00:03';
SELECT 1 AS TEST;
```

From `Event Handlers` create an on `Success` event and choose for example `Export Data`.

Run the query and you'll see at 2 minute mark it will throw an error:

`query1 run failed: {"code":"QUERY_EXECUTION_ERROR","message":"Request Timeout"}`

**Comment by FalkWolsky** [comment]
In v2.4.3 we did set the overall timeout now to 3600s - which is already "crazy".
In the sense of architectural considerations everything above 20-30 sec query time would be solved overall better with an streaming / event based approach. But we also understand, not so easy at many cases, when the number of IT systems should stay small. We hope 3600s should be enough?
