### ISSUE TITLE
[Bug]: Docker (all-in-one) latest - MongoDB entered FATAL state

### ISSUE THREAD

**Issue by cogitomanager** [lowcoder-org/lowcoder#1013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using all-in-one docker-compose, MongoDB fails to start

![image](https://github.com/lowcoder-org/lowcoder/assets/122647286/426a9f88-38c3-477b-ace9-6a87260b4572)

### Expected Behavior

mongodb starts - allowing to register 1st account and start using app

### Steps to reproduce

docker compose up -d using docker-compose.yml (all-in-one)

### Environment

Proxmox VM

![image](https://github.com/lowcoder-org/lowcoder/assets/122647286/8f7c3b9a-9e7f-4fd3-992e-ed85136b1d06)

### Additional Information

using the same docker-compose with arm image works on Oracle Cloud

**Comment by ludomikula** [comment]
When running in virtualbox or other virtualization software (like in your case proxmox) make sure the CPU has the **avx** feature.
Mongodb 5+ (we use version **7.0.1**) requires **avx** CPU feature  - you can check it with: `grep avx /proc/cpuinfo`

Try to set the cpu type of your virtual CPU to **HOST** or something similar (not sure what the options are).

**Comment by adnanqaops** [comment]
This issue can be closed as suggested by Ludo. By following the above [comment ](https://github.com/lowcoder-org/lowcoder/issues/1013#issuecomment-2335145539) from Ludo solves the issue mentioned in this ticket.
