### ISSUE TITLE
[Bug]: currentCell not set for custom mapped columns

### ISSUE THREAD

**Issue by dmacd** [lowcoder-org/lowcoder#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Custom column with explicit data mapping does not set currentCell in the conditional cell color. Value is undefined.

![image](https://github.com/lowcoder-org/lowcoder/assets/40836/6da7d2c0-08e6-429d-911e-3041bfaed72b)

Larger useability issue - regenerating columns from a table that was already automapped when the underlying query changes doesnt work, necessitating adding custom columns and hitting this issue.

### Expected Behavior

currentCell should be set properly in custom column or at least currentRow should be available.

### Steps to reproduce

Create a custom column in a table with an explicit mapping, try to set the conditional cell color for it. See screenshot.

### Environment

lowcoder.cloud

**Comment by dmacd** [comment]
Additional and probably related issue - sort does not work on columns like this.

**Comment by dmacd** [comment]
Okay, apologies for the confusion. No sooner did I post this than the table _did_ manage to auto-refresh (not sure why it didn't the first 5 times I clicked the refresh button) and give me normally mapped columns. But currentCell _still_ doesnt work in the conditional cell color, so perhaps the explicit column mapping was a red herring.

**Comment by raheeliftikhar5** [comment]
This is fixed in v2.4.4
