### ISSUE TITLE
[Bug]: openApi cannot show all paths defined in the swagger scheme

### ISSUE THREAD

**Issue by tiodot** [lowcoder-org/lowcoder#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the path's tags defined in the swagger scheme is empty,  it will be hidden while in the Data Queries.

### Expected Behavior

Show all paths in the Resource filter field:
![image](https://github.com/lowcoder-org/lowcoder/assets/5645617/c39d763c-1a7f-4cb8-940a-75ff582f15fe)

### Steps to reproduce

An example of using openApi for Bamboo Rest API:
1. Config the Data Source with openApi: https://[dac-static.atlassian.com/server/bamboo/swagger.v3.json?_v=1.123.12](https://dac-static.atlassian.com/server/bamboo/swagger.v3.json?_v=1.123.12)
2. Refer the data source in the App page
3. Cannot find the path like: "/responsibility/latest/brokenBuild/{planResultKeyOrPlanKey}/{name}"

**Comment by FalkWolsky** [comment]
It seems this is now thanks to your valuable contribution achieved. Or?
If we miss understood something, please just re-open the issue again.
