### ISSUE TITLE
[Feat]: Implement an Env variable for setting Query Timeout value

### ISSUE THREAD

**Issue by adnanqaops** [lowcoder-org/lowcoder#1028]
**Is your feature request related to a problem? Please describe.**
At the moment, there is a hard coded value set for Query Timeout. This is not so good.

**Describe the solution you'd like**
We should define an Env variable for Query Timeout, and set it's value there.

**Describe alternatives you've considered**

**Additional context**

**Comment by dragonpoo** [comment]
Query timeout is set on datasource config.
Do we have to remove it and add env variable for it?

**Comment by ludomikula** [comment]
No, this is about the default query timeout when you don't set anything in UI: query -> advanced
See [here](https://github.com/lowcoder-org/lowcoder/blob/main/server/api-service/lowcoder-domain/src/main/java/org/lowcoder/domain/query/util/QueryTimeoutUtils.java#L19) and its usage.

**Comment by adnanqaops** [comment]
"LOWCODER_MAX_QUERY_TIMEOUT" Env variable has been implemented for this. This has been done, so closing out this ticket.
