### ISSUE TITLE
[Feat]: Add option to enable/disable "close" in modal popups

### ISSUE THREAD

**Issue by vsnshanmuganathan** [lowcoder-org/lowcoder#1041]
**You can add a switch below modal with text box for this feature**
![Screenshot 2024-07-14 at 9 06 32 PM](https://github.com/user-attachments/assets/1250dc0d-e07a-4acf-81e5-ea4e0c7a7a33)

**How it's helpful**
If some process is happening like loading we can call this modal (modal with loading icon in it) and after success/failure we can close this modal.

**Comment by FalkWolsky** [comment]
Good Idea!!

**Comment by adnanqaops** [comment]
Verified on V2.5.3. It's been implemented, so closing out this ticket.
