### ISSUE TITLE
[Bug]: fetch api not working when Embed App in React

### ISSUE THREAD

**Issue by Just1nWang** [lowcoder-org/lowcoder#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I integrated the application into the react project using lowcoder-sdk, the fetch called in run javascript had no effect.

### Expected Behavior

When I integrated the application into the react project using lowcoder-sdk, the fetch called in run javascript can work.

### Steps to reproduce

1. Add a FormButton
2. Listen Click Event
3. Write Javascript as Follow

```
async function fetch_ip() {
  console.log("1. fetch start")
  try {
    const res = await fetch("https://api.ipify.org?format=json")
    console.log("2. fetch end")
    if (!res.ok) {
      console.log("3. fetch error")
    } else {
      console.log("4. fetch ok")
      const result = await res.json()
      return result
    }
  } catch (error) {
    console.log("5. fetch exception", error)
  }
}

fetch_ip().then(res => {
  console.log("6. fetch result", res)
})
```

4. Embed App in React using lowcoder-sdk 
5. click FormButton in React app
6. check  Chrome DevTools Network, no any request send.

> 

### Environment
"lowcoder": 2.4.2
"lowcoder-sdk": "^2.4.8"

**Comment by Just1nWang** [comment]
I don’t want to upload files through restful data sources or s3 data sources, because lowcoder will proxy my request. Because the file size is usually very large, I will be asked to set lowcoder’s LOWCODER_MAX_REQUEST_SIZE env to a very large value.

**Comment by FalkWolsky** [comment]
In general, this is not supported. JavaScript in Lowcoder does run in a so called sandbox for security reasons.
Our question is - why to put an API call in a JavaScript? Wouldn't it be better to use a Restful API Call as a Data Query and call the query by `yourqueryname.run()`?
Please have a look in the docs:
https://docs.lowcoder.cloud/lowcoder-documentation/business-logic-in-apps/write-javascript/javascript-query#pass-in-parameters
https://docs.lowcoder.cloud/lowcoder-documentation/business-logic-in-apps/write-javascript/javascript-query#restrictions

We close the issue as for now, as it is not really a bug. If you feel we are wrong, please re-open. Maybe we misunderstood you.

**Comment by Just1nWang** [comment]
Here are the two reasons why I don't use the Data Source provided by Lowcoder:

1. When I use Restful API Call as a Data Query, the query timeout is 10 seconds, and there is no way to configure or adjust the timeout duration.
2. When I need to upload files, I use S3 as a Data Query, and the query body is very large. In this case, I would need to adjust the request body size for all requests in Lowcoder, which is not suitable.

@FalkWolsky

**Comment by Just1nWang** [comment]
Another reason is that if fetch is supported, my network request path would be client -> target-server. However, currently, it is client -> lowcoder-server -> target-server, which makes the request path longer and increases the latency.

**Comment by FalkWolsky** [comment]
We agree about the network path, but the added latency should be in the range of 50ms to 100ms.
However, the query timeout is configurable in the advanced tab of data queries.
<img width="864" alt="Screenshot 2024-07-26 at 10 04 27" src="https://github.com/user-attachments/assets/f6913fe0-b6da-4827-a36f-7beb60a06468">

Also, the max request size is configurable - but central via ENV Variable.

LOWCODER_MAX_REQUEST_SIZE and overall LOWCODER_MAX_QUERY_TIMEOUT.


Please have a look here: https://github.com/lowcoder-org/lowcoder/tree/main/deploy/docker

**Comment by Just1nWang** [comment]
Thanks

**Comment by rjamesnw** [comment]
@FalkWolsky I have an API not working because it generates images (Stable Diffusion) and an advanced AI, and both take around or just over 10 seconds, and the lowcoder global query libraries keep timing out after 10 seconds during testing. There is no advanced option for those, so how do I fix that?
