### ISSUE TITLE
[Bug]: Avatar column type causes table component to crash on mouseover event

### ISSUE THREAD

**Issue by James4L** [lowcoder-org/lowcoder#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Any mouseover event of a table component that has a column of type 'avatar' causes the entire table component to crash with an error "Error: Cannot read properties of undefined (reading 'length')."
![image](https://github.com/user-attachments/assets/0161674f-b195-4e37-998c-8b5a6699e853)

### Expected Behavior

The component should not fail

### Steps to reproduce

1. Insert a new table
2. Add a new custom column
3. Change column type to 'avatar'
4. Move your mouse over the table
5. The component will fail

![image](https://github.com/user-attachments/assets/04d238dc-36a1-4d30-b7e3-d5e11de250aa)
![image](https://github.com/user-attachments/assets/b1706c07-2e9b-4efd-ac00-129b63548905)
![image](https://github.com/user-attachments/assets/e20f1ea2-6eb4-4d22-ad4c-bd8f4a6ceb0f)

### Environment

Lowcoder Cloud

### Additional Information

Issue is reproduceable with the default avatars data or custom data. Have tried static or map data source with same result.

If you reload the component, and don't move your mouse over the table, the table component will stay loaded

**Comment by raheeliftikhar5** [comment]
This is fixed in v2.4.4
