### ISSUE TITLE
[Bug]: On Table component, scroll records in non pagination mode not work

### ISSUE THREAD

**Issue by sbash78** [lowcoder-org/lowcoder#1051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

before version 2.4.x table component can supported two modes, with pagination and without pagination.
currently table component does not work without pagination

### Expected Behavior

 You can see example "Table example" from Lowcoder marketplace
https://app.lowcoder.cloud/apps/65e6d71d03a1f229e8c2ac5b/view_marketplace
first table in this example configured wo pagination and after version 2.3.1 not scroll records.
Expected behavior
![2024-07-20_21h06_16](https://github.com/user-attachments/assets/9b33d699-9f88-4302-a6df-a5baddf08808)

### Steps to reproduce

Make new application
Put table component and set table property
Layout - Height = Fixed
Layout - Fixed table header = true
Toolbar - Fixed toolbar = true
Pagination - Hide on single page = true
Pagination - Page Size = 99999

**Comment by FalkWolsky** [comment]
In v2.3.x we also had the option to display or hide the scrollbar.
It is important to get this "feature" back again
