### ISSUE TITLE
[Bug]: Icon button fails to load with "prevent loading styles"

### ISSUE THREAD

**Issue by James4L** [lowcoder-org/lowcoder#1057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the "prevent loading styles" toggle in the global module app settings when a theme is selected, breaks Icon Button component.

"Cannot read properties of undefined (reading 'format')"

It seems that when a theme is selected, this component attempts to read the "Background Color" style property even when "prevent loading styles" is selected at the app settings level. Because the value of "Background Color" is unavailable from the Theme when "prevent loading styles" is selected, the component fails. 

### Expected Behavior

The Icon Button component should not fail when "prevent loading styles" is set with a Theme applied

### Steps to reproduce

1. Start a new component
2. Select a theme in the module app settings
3. Add two Icon Button components
![image](https://github.com/user-attachments/assets/40b0035c-d0f4-4c97-9964-ab161b506a06)

4. Configure one of the two Icon Button components to override the Style > Background Colour value and set a static hex value
![image](https://github.com/user-attachments/assets/0cc5c361-2af5-411e-ad31-09da7aa354fc)

5. Toggle "prevent loading styles" to on in the module app settings
![image](https://github.com/user-attachments/assets/54756995-2f64-4b04-977a-096c919f9617)

6. The Icon Button that does not have a static value for Style > Background Colour will fail to load

Toggling the "prevent loading styles" on the individual component does not alter the behaviour.

### Environment

Lowcoder Cloud as at 24th July 2024

### Additional Information

I tried a handful of other components, including the other button components and did not observe them failing in the same manner. It's possible other components suffer this same issue, I didn't not extensively test it.

**Comment by raheeliftikhar5** [comment]
This is fixed in v2.4.4
