### ISSUE TITLE
[Bug]: DateRange can't be Set or Accessed through Form object

### ISSUE THREAD

**Issue by adnanqaops** [lowcoder-org/lowcoder#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DateRange can't be set or accessed through Form object, when it is placed inside Form object.
Same issue with TimeRange component. 
Please, check other components as well.

### Expected Behavior

DateRange & TimeRange component should be accessible via Form object, when these components are placed inside Form component.

### Steps to reproduce

https://discord.com/channels/1096896040159957084/1096896040650678314/1265699561742012477 

### Environment

Production

**Comment by raheeliftikhar5** [comment]
This is fixed in v2.4.4
