### ISSUE TITLE
[Bug]:  https://app.lowcoder.cloud/apps/ is showing Blank page on Mobile on Sign Up / Login

### ISSUE THREAD

**Issue by adnanqaops** [lowcoder-org/lowcoder#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://app.lowcoder.cloud/apps/ is showing Blank page on Mobile on Sign Up / Login.

### Expected Behavior

https://app.lowcoder.cloud/apps/  page should be accessible on Mobile.

### Steps to reproduce

1. Sign up or Login on Mobile to Lowcoder platform
2. Access this page : https://app.lowcoder.cloud/apps/  
3. You will see a Blank page

### Environment

Production and Local - both

**Comment by FalkWolsky** [comment]
Works now in v2.4.4.
