### ISSUE TITLE
[Bug]: JavaScript code is not triggered for Toast on Page load

### ISSUE THREAD

**Issue by adnanqaops** [lowcoder-org/lowcoder#1074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User reported an issue [here on Discord](https://discord.com/channels/1096896040159957084/1096896040650678314/1267515988744736768) that JavaScript code is not triggered for Toast message when query is run on Page load.

### Expected Behavior

JavaScript code should execute correctly on page load for Toast message, just like it executes normally.

### Steps to reproduce

You can reproduce the issue by going via this App :[Toast Bug - #1074](https://app.lowcoder.cloud/apps/66a7c2a0540028148c6bbc99/edit)

### Environment

Production

**Comment by FalkWolsky** [comment]
Will be solved with v2.4.5
