### ISSUE TITLE
[Bug]: Conditionla Styling is getting reset or removed for components in List View

### ISSUE THREAD

**Issue by yogeshvachhani** [lowcoder-org/lowcoder#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we set any kind of conditional styling to any of the style parameters of a component inside ListView the style gets removed automatically.

For example if we enter this in Edit component's Style -> Text Decoration it gets removed when the screen is refreshed.

The condition that I am using is: {{currentItem.completed?"line-through":""}}

### Expected Behavior

The conditional styling should stay.

### Steps to reproduce

place a Listbox and add a Input component inside it.

In the Input component set the Style for Text Decoration as follows:
{{currentItem.completed?"line-through":""}}

Refresh the page.

**Comment by adnanqaops** [comment]
There was duplicate issue of this : https://github.com/lowcoder-org/lowcoder/issues/1081
I have closed that one. Adding the comment just for reference.

**Comment by vinpro-nz** [comment]
Having same issue with simple text display box setting background color. Static colors work fine but any conditional script appears briefly in preview and then is replaced with previous static color. Returning to editor the conditional color is replaced with previous static color. Have tried "prevent overriding styles" on and off, same result.

**Comment by adnanqaops** [comment]
This issue has been fixed. Conditional Styling is not getting removed after page refresh, So closing out this issue.
