### ISSUE TITLE
[Bug]: Table Component - Shadow keeps moving

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The shadow, which indicates that there are more columns, doesn't stay in its position.
<img width="273" alt="image" src="https://github.com/user-attachments/assets/b5a615a7-2484-4116-aaca-ebdc9972d103">

### Expected Behavior

Shadow not moving

### Steps to reproduce

- Add table with multiple columns
- As soon as you need to scroll horizontally to see all data, you will see it.

**Comment by FalkWolsky** [comment]
We had seen this already and with 2.4.5 it will be fixed.
Shameful silly bug... Agree.
