### ISSUE TITLE
[Bug]: Table - Regenerate Columns doesn't work

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The regenerate columns button doesn't work.
<img width="244" alt="image" src="https://github.com/user-attachments/assets/6db9d7b3-64a2-440c-9746-164a4fe8b3ca">

### Expected Behavior

The columns are regenerated

### Steps to reproduce

- Add a table
- Add a data source
- Generate the columns
- Rename the columns
- Change original data
- Click the button

**Comment by adnanqaops** [comment]
Status update for this ticket : I have tried to reproduce this issue both on Dev and Prod Envs, but it is not reproducing.

**Comment by xjrcode** [comment]
This is happening to me too with exactly the same steps. In my case I create a SQL query with `SELECT *`, renamed some columns and then update the query to `SELECT id, name…` so the update button appears on the columns component. When clic, this error appears on console:
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at index-d1ac9f93.js:855:649
    at Map.forEach (<anonymous>)
    at t.fetchInfo (index-d1ac9f93.js:855:518)
    at Rkr (index-d1ac9f93.js:832:24291)
    at n.value [as fetchInfo] (index-d1ac9f93.js:832:24473)
    at t.fetchInfo (index-d1ac9f93.js:832:27131)
    at Rkr (index-d1ac9f93.js:832:24291)
    at n.value [as fetchInfo] (index-d1ac9f93.js:832:24473)
    at index-d1ac9f93.js:832:28388
```
