### ISSUE TITLE
[Bug]: Table - Column text overlapping

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the column is too narrow, the content is overlapping the next column.
<img width="226" alt="image" src="https://github.com/user-attachments/assets/d09f4c23-fa1c-4ed4-995c-1e5acac5f856">

### Expected Behavior

Hide the content behind the next cell.

### Steps to reproduce

- Add table
- Add data
- Make the width small enough so it overlaps

**Comment by adnanqaops** [comment]
Status update for this ticket : I have tried to reproduce this issue both on Dev and Prod Envs, but it is not reproducing.
