### ISSUE TITLE
[Bug]: White screen after registration/login on Google Chrome 

### ISSUE THREAD

**Issue by gthbstr** [lowcoder-org/lowcoder#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After sign up or log in I get white empty screen on Google Chrome. After refresh page browser redirects to **/apps** and works fine. 

### Expected Behavior

After sign up or login I see **/apps** without white page interruption. 

### Steps to reproduce

1. Deploy self hosted 2.4.5 version
2. Go to https://domain.com and open Lowcoder auth page
3. Create new account or login to existed account
4. Get white page
5. Refresh browser page
6. Get /apps 

### Additional Information

On safari it works, but in google chrome isn't

https://share.cleanshot.com/GYtn5VRJHz7LkzKQs3c2

**Comment by FalkWolsky** [comment]
We have seen this from time to time - but not always - which makes the bug search quite hard. But we are confident to find and fix it soon.

**Comment by gthbstr** [comment]
I see this on self hosted ~ every 3 logins. I try it reproduce in safari about 50 login and logout but it works. The issue is only with google chrome. 

After that I start investigation and start client from source code without babel optimisation. And it works. So I think the problem is around packing code from sources to production ready. 

Do you have news about this issue?
