### ISSUE TITLE
[Bug]: Modules search is broken

### ISSUE THREAD

**Issue by adnanqaops** [lowcoder-org/lowcoder#1123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My newly created Module exist in the "Extensions" section, but if I search it's name, it doesn't appear. 
More details in the video : https://www.loom.com/share/3e47cb43054047c2b96b8c222a012998

### Expected Behavior

Existing Modules should be searchable .

### Steps to reproduce

Steps to reproduce are in the video : https://www.loom.com/share/3e47cb43054047c2b96b8c222a012998

### Environment

Production

**Comment by FalkWolsky** [comment]
We will take the issue and add also support for folder / hierarchy based view to the Modules. The current List can be fast overwhelming.
