### ISSUE TITLE
[Bug]: meta tag in header is faulty

### ISSUE THREAD

**Issue by dizzy-duality** [lowcoder-org/lowcoder#1130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 when viewing an app the following meta tag in the header seems to be faulty
 "\<meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1,user-scalable=noviewport-fit=cover"/>"
 

### Expected Behavior

Seems like there is a comma missing and the header should be like this:
 "\<meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover"/>"

### Steps to reproduce

open an app and check the header of the page

### Environment

Chrome

**Comment by FalkWolsky** [comment]
Thank you very much for this finding and clear description. We did find it and it will be fixed with v2.4.6

**Comment by dizzy-duality** [comment]
> Thank you very much for this finding and clear description. We did find it and it will be fixed with v2.4.6

My pleasure! love lowcoder

**Comment by FalkWolsky** [comment]
We did fix it already (available in the Docker images with "dev" tag. Will be part of v2.4.6 then automatically.
