### ISSUE TITLE
[Bug]:  api-service module server start error, missing class QInvitation 

### ISSUE THREAD

**Issue by hefeng6500** [lowcoder-org/lowcoder#1141]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

idea run api-service module server

![image](https://github.com/user-attachments/assets/ef8b02c4-086f-4d8c-88f1-6865d82725f0)

### Expected Behavior

start running success!

### Steps to reproduce

Please add QInvitation Class in org.lowcoder.domain.invitation.model folder

### Environment

- windows 11
- maven v3.9.6
- java SDK 17.0.10

### Additional Information

https://github.com/lowcoder-org/lowcoder/blob/main/server/api-service/lowcoder-domain/src/main/java/org/lowcoder/domain/invitation/repository/CustomInvitationRepositoryImpl.java

line 7: `import org.lowcoder.domain.invitation.model.QInvitation;`

**Comment by ludomikula** [comment]
All model **Q**-classes are generated during compile time by Query DSL. Please use maven compile goal to build them.
