### ISSUE TITLE
[Bug]: Cannot type properly into rich text editor

### ISSUE THREAD

**Issue by kmbuthia** [lowcoder-org/lowcoder#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Typing into the rich text editor component is quite buggy. The cursor seems to move around and jumble the letters as you type. It only works if you type very slowly, making it unusable. Inspecting the rich text editor html with the browser console shows that it seems to be re-rendered constantly with every key stroke which may be the cause of the issue.

FYI I have seen similar behaviour using the "Scripts and Styles" feature on the front-end when writing CSS or JS...in that situation the cursor jumps to the top line every few seconds making it difficult to use.

### Expected Behavior

The cursor should not jump around and I should be able to type quickly or slowly.

### Steps to reproduce

1. Using the front-end, drag the rich text editor onto the canvas.
2. Attempt to type words into it.
3. Try the same in preview mode (same cursor jumping and jumbled letter behaviour)

https://github.com/user-attachments/assets/fb300e7d-4827-4afa-a15e-e9d2d17e68b1

### Environment

Lowcoder version 2.4.5
Running docker image version 2.4.5 (CE edition)

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by kmbuthia** [comment]
Just to clarify @FalkWolsky is this fixed in the new release?

**Comment by FalkWolsky** [comment]
Yes

**Comment by kmbuthia** [comment]
Amazing, thanks so much. Looking forward to trying it out once I update! 🙏🏽
