### ISSUE TITLE
[Bug]: List of issues found while testing V2.4.6 on Dev

### ISSUE THREAD

**Issue by adnanqaops** [lowcoder-org/lowcoder#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. JS query is not running automatically on Page Load. More Details here [on Discord Thread](https://discord.com/channels/1096896040159957084/1096896040650678314/1284073871200485529) ( both Local and Prod )
2.  On dev branch, workspace folder names are now getting wrapped in ellipsis regardless of the name length. We can remove the ellipses, I think. 
3. App Editor doesn't following the Logic of the updated Site Title logic. It's working fine on Publish/Preview link, though.

 

### Expected Behavior

Kindly, Fix the above issues

### Steps to reproduce

Steps to reproduce are explained above.

### Environment

Local V2.4.6

**Comment by mat02** [comment]
Regarding bug 1:

If I JS query name is used inside that query, even inside string, then triggering at page load stops working:
![image](https://github.com/user-attachments/assets/f92db787-667b-41d7-a755-f870f6870a47)
[JS Query bug.json](https://github.com/user-attachments/files/17010828/JS.Query.bug.json)

**Comment by adnanqaops** [comment]
Issues mentioned in 1st and 3rd points have been fixed, and are released. Issue in Point # 2 is minor one, and I have noted it separately. So, closing out this ticket.
