### ISSUE TITLE
[Bug]: App editing is blocked in Self-hosted

### ISSUE THREAD

**Issue by blaszta** [lowcoder-org/lowcoder#1232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create new app/navigation and it will automatically show this message
![someone is editing this page 2](https://github.com/user-attachments/assets/1194aa45-0f05-47ea-93f4-ca646783aaa1)
This is a brand new Lowcoder instance (using docker compose) and I'm the only user.
I try to logout and login again, still the same. Try 2 different browser (Firefox and Edge, all latest version) still the same.

### Expected Behavior

User can edit app immediately.

### Steps to reproduce

From Home, create new App/Navigation (haven't test with creating new Module)

### Environment

Self-hosted using docker compose.
version: 
![version](https://github.com/user-attachments/assets/06a00858-415d-461b-ad52-0a3e021650c3)

**Comment by adnanqaops** [comment]
Hello @blaszta , This was an issue in V2.4.6, but we have fixed it in the latest version of Lowcoder ( V2.4.9 ).
I am closing out this issue, but please re-open it again if you still get this issue.
