### ISSUE TITLE
[Feat]:Move apps to workspace

### ISSUE THREAD

**Issue by datos-crea** [lowcoder-org/lowcoder#1248]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow reorganize apps in workspaces. The possibility to select one app in some workspace and allow to move it to another ws.

**Comment by adnanqaops** [comment]
Hello @datos-crea , This feature is already there on Lowcoder.  Here's how you can do it : 

1. Click on the three dots on the right side of an App.
2. Click on "Move Folder" option.
3. Select your desired Folder.
4. Click "Move" button to complete the process.

For now, I will close this feature request. Let me know in case of any confusion or other issues. Thank you.
