### ISSUE TITLE
[Bug]: OAuth: User cannot log in through different orgs

### ISSUE THREAD

**Issue by jnewman-eti** [lowcoder-org/lowcoder#1284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user logs into lowcoder through oauth provider into one org, logs out, and logs into a different org, this causes an error.

It seems the connection data stored in the db is not handled in a way that facilitates a user to log into different orgs.

Our setup: Keycloak with multiple orgs.  Users can exist on both orgs.
Lowcoder Generic Oauth Provider.

### Expected Behavior

If a user logs out, and logs back in through a different org, the system should be able to handle this case without causing an error.

### Steps to reproduce

Have a multitenant setup in your IDP.
Register the same user in 2 orgs.  Same name, email, etc.

Set up the Generic Oauth provider to authenticate through keycloak.
Log into lowcoder using org 1.
Log out of org 1.
Log into org 2.
This should cause an error.

### Environment

Lowcoder version 2.4.x
Keycloak IDP

**Comment by FalkWolsky** [comment]
Question... Do you mean Lowcoder Orgs or KeyCloak Orgs (realms)?

**Comment by dragonpoo** [comment]
@jnewman-eti 
I fixed the issue and it is not reproduced on my side.
Hope you retest it.
Thanks

**Comment by dragonpoo** [comment]
After this [PR](https://github.com/lowcoder-org/lowcoder/pull/1330) is being merged, of course

**Comment by adnanqaops** [comment]
This issue has been fixed in V2.5.1. So, closing out this issue.
Kindly, feel free to open it again if you face this issue again.
