### ISSUE TITLE
[Bug]: uuid does not seem to execute on selection change trigger

### ISSUE THREAD

**Issue by WinstonPoh** [lowcoder-org/lowcoder#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First of all **thank you** for continuing this **awesome** work! This is an great project and I'm really enjoying trying it out.

I have created a form with a **selection dropdown**, that triggers on **Changed** event to set a **temporary state** to the value **uuid.v1()**.
![Screenshot from 2023-05-11 11-28-31](https://github.com/lowcoder-org/lowcoder/assets/7601526/3892ade9-98ff-4706-9e85-f596263b14f2)

As you can see in the image, uuid.v1() does run and the state is set correctly, which is great. However, it **does not trigger when the selection is changed** each time, or perhaps, it _does_ run uuid.v1() but the value is the same somehow.

I opened up the browser console and running uuid.v1() repeatedly gave random uuids as expected

Thanks in advance!  

### Expected Behavior

I expected `project_state.id` to be updated to a new random UUID each time the selection is changed for the dropdown

### Steps to reproduce

1. create a new app
2. add a new Select component
3. add a new temporary state
4. add Select component's Properties > Interaction > Event handler like so:
![Selection_028](https://github.com/lowcoder-org/lowcoder/assets/7601526/d791be4f-d5e1-438a-b78c-7ae84f97e2d1)
5. open up temporary state on left sidebar to view its value
6. change selection for the Select component between the default Options 1 and 2.
7. The temporary state remains the same value when it should have changed each time randomly

### Environment

Ubuntu, just trying it out on https://app.lowcoder.cloud/

**Comment by falnyr** [comment]
Thanks for raising this 👍

**Comment by WinstonPoh** [comment]
Nice solution, but I would expect the {{uuid.v1}} under Action to be running the uuid.v1() function as JS, which is why I think it is a bug.
![Selection_028](https://github.com/lowcoder-org/lowcoder/assets/7601526/d791be4f-d5e1-438a-b78c-7ae84f97e2d1)

**Comment by Vayras** [comment]
@falnyr Can I contribute towards this issue?

**Comment by FalkWolsky** [comment]
No, this is not a bug. If you want to bind it dynamically, then please use the Javascript execution at the Event-Handler and set the Value of the Temporary state from there.
