### ISSUE TITLE
[Bug]: chartsGeoMap component is not loading/working

### ISSUE THREAD

**Issue by vsnshanmuganathan** [lowcoder-org/lowcoder#1292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This component does not load even after implementing the correct API key.
![Screenshot 2024-11-11 at 4 51 58 PM](https://github.com/user-attachments/assets/ce5b65e1-7027-43b3-ab66-230ad5203030)

### Expected Behavior

The component should load the maps without any issues.

### Steps to reproduce

Simply drag the GeoMap component and enter the Google Maps API key.

### Environment

Lowcoder latest version on Docker

**Comment by adnanqaops** [comment]
I have tried this issue on Cloud and Local, but it is not reproducing for me.

**Comment by vsnshanmuganathan** [comment]
> I have tried this issue on Cloud and Local, but it is not reproducing for me.

in v2.5.0 it works fine
