### ISSUE TITLE
[Bug]: The Drawer component is not scrolling in both the Editor and Frontend UI.

### ISSUE THREAD

**Issue by vsnshanmuganathan** [lowcoder-org/lowcoder#1296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If there are many components inside the Drawer, we cannot scroll vertically, making all the components unusable.

### Expected Behavior

It should scroll vertically until it reaches the end of the container.

### Steps to reproduce

Import the project below, and it will be easy to replicate the error.
[test2.json](https://github.com/user-attachments/files/17705497/test2.json)

### Environment

The latest version of Lowcoder on Docker.

### Additional Information

Please ensure that the Header/Close button remains fixed and does not scroll while addressing this issue, as we are unable to close the drawing otherwise.

I've included a short video below for reference.

https://github.com/user-attachments/assets/e0cd95f7-deec-45cd-946b-b81680b6952e

**Comment by raheeliftikhar5** [comment]
Solved in v2.5
