### ISSUE TITLE
[Bug]: The Esc button closes the Drawer even when 'Enable Close Button' is set to false

### ISSUE THREAD

**Issue by vsnshanmuganathan** [lowcoder-org/lowcoder#1298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It works fine, but when we press the Esc key on the keyboard, it closes the Drawer, even though the 'Enable Close Button' is set to false.

### Expected Behavior

It should not close when the Esc button is pressed.

### Steps to reproduce

Drag the Drawer component, then disable the "click outside to close" option and also turn off the "enable close button" option.

### Environment

Lowcoder latest version on Docker

### Additional Information

Check the Modal component for correct behavior.

**Comment by raheeliftikhar5** [comment]
Solved in v2.5

**Comment by raheeliftikhar5** [comment]
Solved in v2.5
