### ISSUE TITLE
[Bug]: OnMouseover overflow text in tables has lost background opacity in v2.4.12

### ISSUE THREAD

**Issue by lanedsmu** [lowcoder-org/lowcoder#1300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When hovering over text in a table, where the text runs longer than the column, the text is displayed without a background, such that the text becomes unreadable.

The overflow text that shows is correct and--I believe--in the correct location.  The background of the popup text is transparent, however, so the text is largely unreadable on top of other text.
![image](https://github.com/user-attachments/assets/4a30005e-9992-4fd3-bf33-8df7702f6bc7)

### Expected Behavior

Pop up text will hide the text behind it

### Steps to reproduce

mouseover a table field with text that is too long to fit in the cell

**Comment by gboxxx** [comment]
I'm on latest (2.5.3.) and still experiencing this behavior. 

![CleanShot 2024-12-25 at 11 25 11 3@2x](https://github.com/user-attachments/assets/e2edb4a5-2077-4985-bdbf-f48ef0f21b51)
