### ISSUE TITLE
[Bug]: Responsive layout hides other columns, which makes it unresponsive.

### ISSUE THREAD

**Issue by vsnshanmuganathan** [lowcoder-org/lowcoder#1311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's not responsive; it hides other columns from the screen, and this has been tested on both PC and mobile.

https://github.com/user-attachments/assets/0b2ae8d4-3dea-4e3c-ada8-a56063a00135

### Expected Behavior

It should be responsive, and the columns should be aligned according to the properties.

### Steps to reproduce

check above video or import below project.
[test-auto.json](https://github.com/user-attachments/files/17784719/test-auto.json)

### Environment

Lowcoder v2.4.12 on docker

**Comment by FalkWolsky** [comment]
We tested it and cannot confirm this new behaviour. It seems to still work as expected.
Question... Did you activate the switch "Row break"?
Please re-open if the issue persists for you, so we can check deeper.

**Comment by vsnshanmuganathan** [comment]
I haven't switch ON "Row break" and if i turn on it's working fine.
