### ISSUE TITLE
[Bug]: In the listApplications API, the FolderID is null for all apps, even though they are inside a folder.

### ISSUE THREAD

**Issue by vsnshanmuganathan** [lowcoder-org/lowcoder#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`"role": "owner",
"applicationType": 1,
"applicationStatus": "NORMAL",
"folderId": null,`

### Expected Behavior

It should return the FolderID if the app is inside a folder when using the `/api/applications/list` API query.

### Steps to reproduce

run this API `/api/applications/list` as per [docs](https://docs.lowcoder.cloud/lowcoder-api-specification/api-reference-lowcoder/api-lowcoder-v2.0.1/applications/list)

### Environment

lowcoder 2.5.0

### Additional Information

This helps me back up apps and apps inside folders easily. Currently, I take multiple backups of some apps.

**Comment by adnanqaops** [comment]
This has been deployed in V2.5.3, So, closing out this ticket.

**Comment by vsnshanmuganathan** [comment]
@adnanqaops the above issue was solved and so i can skip those apps inside the folder during backup,
but if i try below ```/api/folders/elements```
![Screenshot 2024-12-24 at 2 48 59 PM](https://github.com/user-attachments/assets/1821c793-356f-49da-9f22-dc369b3117f5)
i don't get folderId it's null, 
![Screenshot 2024-12-24 at 2 51 14 PM](https://github.com/user-attachments/assets/eda7e229-7e25-4f75-aca4-bb568a679010)
so here i can't skip the apps which was not in folder or take only apps which was in folder viceversa,
let me know will this be solved in future release or i need open a new ticket for this issue.

**Comment by vsnshanmuganathan** [comment]
@adnanqaops i could get folderId `null` by calling view apps ```/api/applications/appId/view```

**Comment by dragonpoo** [comment]
@adnanqaops @vsnshanmuganathan @FalkWolsky @ludomikula 
Here is [PR](https://github.com/lowcoder-org/lowcoder/pull/1439) for adding the folderID to all applicationInfoViews
