### ISSUE TITLE
[Bug]: super_admin is less powerful than admin

### ISSUE THREAD

**Issue by KarlKeu00** [lowcoder-org/lowcoder#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- A super_admin cannot change the authorisations of other members.
- A super_admin cannot rename or delete their own organisation.

### Expected Behavior

Well, a super admin should be allowed to manage their own organisation just like a normal admin.

### Steps to reproduce

1. Set up a new installation.
2. Log in with the super_admin.
3. Rename your own organisation or change a user's role.

**Comment by vsnshanmuganathan** [comment]
I can't create a theme too as super admin

**Comment by adnanqaops** [comment]
This has been fixed in V2.5.1. So, I am closing out this issue.
