### ISSUE TITLE
[Bug]: Global variables not avialble when navigating between apps

### ISSUE THREAD

**Issue by iceman91176** [lowcoder-org/lowcoder#1340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When navigating between app with the "Go to an other app" event-handler global-variables are not available in the "target-app".
This does not happen every time, but sooner or later it happens when navigating between apps.

It never happens when using the full URL of the published apps to navigate between the apps. But in this case the whole page is loaded which results in longer loading times (and hard-coding the URLs is kind of an anti-pattern)

### Expected Behavior

Global variables must always be available when navigating with "Go to an other app"

### Steps to reproduce

As mentioned it can't be reproduced every time. We were able to trigger it with 2 simple app each with a button that navigates to the other app and a json-explorer that displays the "screeninfo" variable. Somtimes the variable is empty, sometimes it's not.

### Environment

Docker, using the lowcoderorg/lowcoder-ce:latest image (checksum 99cdd8f4ea74b82d96026e9a6ad2f56bb48e9fb8f7edf967bf58d1d707bdda31). Tested with different browsers (firefox 128.4.0esr , chrome 131.0.6778.86)

**Comment by FalkWolsky** [comment]
We think this is maybe a race condition. It may not have anything to do with the mechanism of "Go to an other app" - but would appear simply by loading the same app 100 times for few occurrences?

**Comment by iceman91176** [comment]
Well, actually it is happening sooner than after 100 times ;-) You are right, it could be a race condition. We have an app where it happens almost instantly, while in others it never happens.
Could be a wild guess, but apps that have a lot going on (queries, scripts, etc.) seem to suffer more from it.

**Comment by adnanqaops** [comment]
This has been fixed and deployed in V2.5.3. So, closing out this ticket.
