### ISSUE TITLE
[Bug]: When one app links to another app, sometimes the page does not load properly when traveling from app A to app B.

### ISSUE THREAD

**Issue by jnewman-eti** [lowcoder-org/lowcoder#1388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you have an app that opens another app, sometimes the global data variables are lost, the oauth gets broken, and the app will not load properly.  This causes the user to need to refresh the current page and sometimes even refresh doesn't work.  We have apps with queries that fire on page load, and it seems when there is a more complex application this issue happens more frequently.  The global data variables also disappear when clicking through history states of the app.  This happens every time.

This is reproducible in 2.3.x, 2.4.x, and app.lowcoder.cloud.

### Expected Behavior

The applications should resolve global data variables and load the pages correctly.

### Steps to reproduce

Create app A, and app B.
Put a button on both apps, with the event "open another application".  
In app A, on button click open App B.
In app B, on button click open App A.

On this simple app with nothing else going on, you may need to click the buttons in a more rapid succession.  At some point, you will see the global data variables disappear.  This seems to happen randomly.

### Environment

app.lowcoder.cloud

**Comment by jnewman-eti** [comment]
Apologies, it did not show up for some reason when searching issues before I created this ticket

**Comment by adnanqaops** [comment]
This has been fixed and deployed in V2.5.3. So, closing out this ticket.
