### ISSUE TITLE
[Bug]: <charts not working Error component not found>

### ISSUE THREAD

**Issue by dalmarazr** [lowcoder-org/lowcoder#1405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I try to use the lowcoder chart component that are based on echarts library it thows an empty component with the error :  "Error: Component basicChart Not found", all the charts present this error, mermaid, sankeyChart, chart, geoMap.

On console I see this error: Error during remote component loading TypeError: Cannot read properties of undefined (reading 'map')
    at Module.K6 [as styleControl] (:3000/static/index-634f5406.js:6361:655)
    at :3000/api/npm/package/6765af04e820097199224249/lowcoder-comps@2.5.3/e2b07149.js:146087:29
![components not found](https://github.com/user-attachments/assets/4d653bd6-1efa-4e31-96de-0913db178041)
![console error](https://github.com/user-attachments/assets/738996f8-e364-4b84-bdf0-b0e367e4d65b)
![properties pane not loading for charts](https://github.com/user-attachments/assets/425054ed-9273-4bba-8fd4-bcd5d7f6b758)
,

### Expected Behavior

Drag and drop a chart and be able to edit it

### Steps to reproduce

fresh installation of lowcoder, 
1.- curl https://raw.githubusercontent.com/lowcoder-org/lowcoder/main/deploy/docker/docker-compose.yaml -o docker-compose.yml
2.- docker-compose up -d
3.- login as admin at localhost:3000/
4.- create app/module
5.- drag and drop a chart component

### Environment

fresh installation

### Additional Information

I tried downgrading to 2.4.11 , 2.4.12 and the error still occurs

**Comment by vsnshanmuganathan** [comment]
fixed in latest version 2.5.3,
update lowcoder
