### ISSUE TITLE
[Bug]: Input value does not get updated with some default values in listview

### ISSUE THREAD

**Issue by enuit** [lowcoder-org/lowcoder#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have some TextInput within a ListView. When I change the value of this TextInput, an event opens a notification with the current value of the TextInput. With some default values of the TextInput, the user input in this TextInput is not written in the notification. 

This happens for example when the default value is taken from an object written in a temporary state. When I access the same value outside of a ListView, the notification gets the updated value as expected. When I build a trivial temporary state (i.e. just a string) the notification also receives the updated value correctly, even within the ListView.

Attached is a screenshot, where I update "input1", but the notifcation doesn't see that.

![image](https://github.com/lowcoder-org/lowcoder/assets/31141874/4554c004-cb59-4d85-8171-3ddc1da3cf47)

### Expected Behavior

Referring to the screenshot, I would expect the notification to show: 

`Der wert ist: "State1 Variable 1 updated"`

### Steps to reproduce

Reproducing the problem and playing around with the problem should be possible by importing this JSON:
``` 
{"applicationInfo":{"name":"exampleapp","createAt":1684753735243,"createBy":"646b4d3c2071810ba72f0f61","applicationId":"646b4d472071810ba72f0f73","applicationType":1},"applicationDSL":{"ui":{"layout":{"c656489f":{"i":"c656489f","h":18,"w":10,"delayCollision":true,"x":4,"y":13},"fe819418":{"i":"fe819418","h":5,"w":5,"x":4,"y":32}},"items":{"c656489f":{"compType":"listView","comp":{"noOfRows":"{{state1.value[\"value\"]}}","noOfColumns":"1","itemIndexName":"i","itemDataName":"currentItem","dynamicHeight":"auto","heightUnitOfRow":"1","container":{"layout":{"bf09b461":{"i":"bf09b461","h":5,"w":13,"x":0,"y":0},"e7e6ff80":{"i":"e7e6ff80","h":5,"w":11,"x":13,"y":0}},"items":{"bf09b461":{"compType":"input","comp":{"value":"{{state1.value[\"value\"][i][\"name\"]}}","label":{"text":"Label","width":"33","widthUnit":"%","position":"row","align":"left"},"onEvent":[{"name":"change","handler":{"compType":"message","comp":{"text":"Der wert ist: \"{{input1.value}}\"","level":"info"},"condition":"","slowdown":"debounce","delay":""}}],"validationType":"Text"},"name":"input1"},"e7e6ff80":{"compType":"input","comp":{"value":"{{state2.value}}","label":{"text":"Label","width":"33","widthUnit":"%","position":"row","align":"left"},"onEvent":[{"name":"change","handler":{"compType":"message","comp":{"text":"{{input3.value}}","level":"info"},"condition":"","slowdown":"debounce","delay":""}}],"validationType":"Text"},"name":"input3"}}},"autoHeight":"auto","pagination":{"changeablePageSize":null,"pageSize":"6","pageSizeOptions":"[5, 10, 20, 50]"}},"name":"listView1"},"fe819418":{"compType":"input","comp":{"value":"{{state1.value[\"value\"][0][\"name\"]}}\n","label":{"text":"Label","width":"33","widthUnit":"%","position":"row","align":"left"},"onEvent":[{"name":"change","handler":{"compType":"message","comp":{"text":"{{input2.value}}","level":"info"},"condition":"","slowdown":"debounce","delay":""}}],"validationType":"Text"},"name":"input2"}}},"tempStates":[{"name":"state1","value":"{\"value\": [{\n  \"name\": \"State1 Variable 1\",\n}, {\n\n  \"name\": \"State1 Variable 2\",\n}]}"},{"name":"state2","value":"\"state2 variable\""}],"refTree":{"value":"","items":[{"value":"state1"},{"value":"state2"}]},"hooks":[{"compType":"urlParams","comp":{},"name":"url"},{"compType":"momentJsLib","comp":{},"name":"moment"},{"compType":"lodashJsLib","comp":{},"name":"_"},{"compType":"utils","comp":{},"name":"utils"},{"compType":"message","comp":{},"name":"message"},{"compType":"localStorage","comp":{},"name":"localStorage"},{"compType":"currentUser","comp":{},"name":"currentUser"},{"compType":"theme","comp":{},"name":"theme"}],"settings":{"maxWidth":{"dropdown":"1920","input":0},"themeId":"default"},"preload":{"script":"","css":""}}}
```
When you have opened this app, change the value of the fields and see which match your expectation. Every notification should return what is currently written in the field you change.
### Environment

Current Docker Mainline (https://raw.githubusercontent.com/lowcoder-org/lowcoder/21e92bde50125e736f6de6e8698fb2175ef91757/deploy/docker/docker-compose.yaml)

**Comment by aaron1604** [comment]
Hey @enuit 

Thanks for reporting. This is a known and complex issue. It happens because of the list view. We will be working on it and fix this but it will require time as It is complex.

For now, You can use the default value as a placeholder and then it should work. On the notification side, You can use conditional value as below.

```
{{input1.value == ""? state1.value.value[i].name : input1.value}}
```

This should solve your problem temporarily. As well as, As FYI: an `input1.value` you will always get the first input value because of the same reference. We will be refactoring this behavior and solving it in the future. As well as Will be more than happy if you can work on your side and raise the PR of solving it.
