### ISSUE TITLE
[Bug]: Custom components cannot be used

### ISSUE THREAD

**Issue by ljm000** [lowcoder-org/lowcoder#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I place the custom component to the canvas.
The code in the settings is not working.
Only the following is shown:

<img width="623" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/12406935/baf2fee9-bd55-408f-87c9-efd1f96d4468">

The component found in the code snippet of the custom component will visit the specific address by default.

<img width="780" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/12406935/a91e95a7-f7ed-4653-aaf2-c06d1dda6c38">

<img width="608" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/12406935/3d9c155b-a0bd-4daf-942d-f0672c2993b9">

Components will access:
https://custom-component.lowcoder.dev/index.html

### Expected Behavior

Implement the description in the following documentation on the custom component
https://github.com/lowcoder-org/lowcoder/blob/main/docs/build-apps/component-guides/custom-component.md

### Steps to reproduce

In the app editor, drag and drop custom components onto the canvas.

**Comment by falnyr** [comment]
Thanks for a detailed bug report, this is a leftover from rebranding.

**Comment by thanosits** [comment]
Hello to everyone, I would like to ask you, if anyone knows, the content of https://custom-component.lowcoder.dev/index.html or https://custom-component.openblocks.dev/index.html

Thank you!

**Comment by falnyr** [comment]
Hey @thanosits, the original code lives here: https://custom-component.majiang.co/index.html. This is the Chinese version of Openblocks that all our code is based on. We need to create a build pipeline that will push to a similar location for Lowcoder.

**Comment by billyrudi** [comment]
do you have timing for fix it?

**Comment by ljm000** [comment]
> do you have timing for fix it?

NO
https://github.com/lowcoder-org/lowcoder/pull/180
Mention needs to be fixed via pipeline or NPM.
But I don't know how to do it.

**Comment by falnyr** [comment]
This should now be resolved by #201, can you please check?

**Comment by ljm000** [comment]
> This should now be resolved by #201, can you please check?
normal functioning!
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/0f5d98a2-c6d0-4362-bb97-d049f95c72e5)
