### ISSUE TITLE
[Bug]: I can't select with condition "IN" in MSSQL

### ISSUE THREAD

**Issue by dumy** [lowcoder-org/lowcoder#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I make the selection, it does not display the data. When I take the string in management studio work this query
SELECT * FROM Users WHERE Id in ('8E965D1A-8EB8-43CA-B2C6-5E81946B4BC8', '14CC7614-FFFC-4DC0-9669-57E84BCBC522', 'CB32D41B-3FCC-4DD6-B546-B2477AC001C3', 'A5DCFAFD-3C 69-4CD8 -9840-E4C3D86D03F1', '8E3D5C2D-F5EB-4C54-88CE-64C98EBBB6D2', '4C7AF14B-83E5-4B72-B5C4-0C50743F6AF8', '3F534757-713E-4907-B09B-345D0 B4ED8DA');

![image](https://github.com/lowcoder-org/lowcoder/assets/8275027/308bb835-25fe-46c5-bd28-2f685e75ca46)

### Expected Behavior

7 rows from the table should be displayed

### Steps to reproduce

1. Add SQL Server
2. Write Query SELECT col1 FROM Users WHERE Id in ('8E965D1A', 'A5DCFAFD')
3. and run

**Comment by falnyr** [comment]
Can you provide additional details? E.g. version of MSSQL and schema for the table you're selecting from?

Also, have you tried using a different connection? E.g. similar query from a different table?

**Comment by dumy** [comment]
if is number I don't have a problem but it's is iterate from srting then don't return nothing. In all tables in all version of SQL Server

**Comment by dumy** [comment]
in MySQL is simple and work
![image](https://github.com/lowcoder-org/lowcoder/assets/8275027/df560c8f-8064-49e1-9314-b6c77803538c)

**Comment by MichalisDBA** [comment]
@dumy If you profile the query while it runs you can see that the query is executed as stored procedure and adds additional quotes ''.

Your query works. To make it work with openblocks, go to the Data Sources for your MSSQL data source, check the `Enable toggling prepared statements for queries` then go to your query -> advanced tab and check `Disable prepared statements`

**Comment by dumy** [comment]
it's is one value it's work 
![image](https://github.com/lowcoder-org/lowcoder/assets/8275027/8bb6f9af-bc7e-44a6-8891-4025fe739dc6)

if is two value don't show any from table.

* it was disabled for me

**Comment by MichalisDBA** [comment]
Please check again to make sure prepared statements are disabled. For me with your example works perfectly

![image](https://github.com/lowcoder-org/lowcoder/assets/68512501/9577a537-0d9f-4779-b3bf-89f8b6c708f0)

![image](https://github.com/lowcoder-org/lowcoder/assets/68512501/9cf76db6-349c-4346-a101-ac79e3e40881)

**Comment by dumy** [comment]
Thx, problem solved, I'm so happy

**Comment by Howe829** [comment]
Hi, I encountered the same issue using postgrsql, but I don't have the "Disable prepared statements" option.What should i do?
![WX20240618-163726@2x](https://github.com/lowcoder-org/lowcoder/assets/28386363/f1e0a3b3-489d-486c-917f-96f73e9be6f4)
<img width="669" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/28386363/5bb64db2-078f-4104-9061-c314c940fd63">
Please help.
