### ISSUE TITLE
[Bug]: Calendar translation

### ISSUE THREAD

**Issue by billyrudi** [lowcoder-org/lowcoder#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1723" alt="Screenshot 2023-06-08 alle 23 01 30" src="https://github.com/lowcoder-org/lowcoder/assets/11408614/5ef3919d-a77d-40a2-b433-95bd7f4d85b3">

### Expected Behavior

Please correct translation!

### Steps to reproduce

On mobile device

**Comment by billyrudi** [comment]
![immagine](https://github.com/lowcoder-org/lowcoder/assets/11408614/5d50605e-07ee-48e8-aead-7bd410e88800)

**Comment by FalkWolsky** [comment]
This will be finally fixed in Version v2.4 - please excuse the long waiting!
