### ISSUE TITLE
[Feat]: Click event for container component

### ISSUE THREAD

**Issue by gehtalles-de** [lowcoder-org/lowcoder#214]
**Describe the solution you'd like**
I'd like to suggest adding a "clicked" event to the container component because it's a common design pattern and people are used to it.

**Comment by FalkWolsky** [comment]
The event capabilities across all components are a bit mixed. We have to clean it up definitely.
Have a look here for example. https://app.lowcoder.cloud/apps/648cd237a0308d4efcc64571/view
We created an app, that lists all available components, their possible events, and style. It is quite wild distributed and needs attention from us.

**Comment by FalkWolsky** [comment]
A Container can contain Components and is as such pretty focussed to do this. We think that non-pure-Layout components should have these events - but the container as other layout components are to give layout of an app a structure. They are not user-interaction elements to our understanding. We will close the issue. If there is a voting of many users for it, naturally we would re-open and implement it as feature.
