### ISSUE TITLE
[Feat]: Add the option to hide the table footer

### ISSUE THREAD

**Issue by gehtalles-de** [lowcoder-org/lowcoder#218]
**Is your feature request related to a problem? Please describe.**
I have a case where I don't need the user to download or filter the data. Moreover there's no need of pagination. I have disabled these features and the table footer is still there, as a white space without function. 
<img width="1174" alt="Bildschirmfoto 2023-06-18 um 08 49 55" src="https://github.com/lowcoder-org/lowcoder/assets/70889776/ef1ea2a2-80d8-417a-bb19-b60ed48df1d6">

**Describe the solution you'd like**
I'd like to be able to hide the table footer like I can with the header.

**Comment by FalkWolsky** [comment]
This option exists already but is a bit hidden. It is in the toolbar section "Position". When you select the right "-" option, it hides the toolbar.
 
<img width="308" alt="Screenshot 2023-07-02 at 12 41 37" src="https://github.com/lowcoder-org/lowcoder/assets/3671017/fb47856e-2226-492c-b28d-9fe6c9a922c5">
