### ISSUE TITLE
[Feat]: Add a way to reset password

### ISSUE THREAD

**Issue by tcfly** [lowcoder-org/lowcoder#221]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to reset a password on [Lowcoder Cloud](https://app.lowcoder.cloud/) if you have forgotten it. This can be a problem if you have lost access to your email address or if you have been hacked. 

**Describe the solution you'd like**
I suggest that Lowcoder add a way to reset passwords, such as by sending a password reset link to the user's email address or by allowing users to answer security questions to reset their passwords.

**Comment by hexifox** [comment]
Hey guys! Loving the product so far, but cannot access my account because of this issue.. Any progress on this?

**Comment by FalkWolsky** [comment]
Finally this is possible now since Lowcoder 2.4.0. An Admin user will set an SMTP Server, so the password reset eMail can get sent to the users.
