### ISSUE TITLE
[Feat]: Allow to export/import themes

### ISSUE THREAD

**Issue by LomigFR** [lowcoder-org/lowcoder#224]
**Is your feature request related to a problem? Please describe.**
Hi there!
An idea for a new feature: would it be possible to export/import themes, plz?

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by FalkWolsky** [comment]
[Export Import Themes.zip](https://github.com/lowcoder-org/lowcoder/files/11931311/Export.Import.Themes.zip)

We made a possibility to use the Lowcoder API to export and import Themes.
However, in future, we want to support this natively in the App.

When you imported the Apps, you need to follow the steps to create the local Open Rest API of Lowcoder as Datasource.
Please find a guide here: https://docs.lowcoder.cloud/lowcoder-documentation/lowcoder-extension/lowcoder-open-rest-api

When you have created the new Datasource, please update both apps for the OpenAPI Requests with your new Datasource.

**Comment by jymcheong** [comment]
@FalkWolsky is there a guide with steps to show how this is done?

I tried reviewing https://docs.lowcoder.cloud/lowcoder-api-specification/api-reference-lowcoder/api-lowcoder-v2.1.6 but both browsers types are hitting errors when browsing the docs.
