### ISSUE TITLE
[Feat]:Autocomplete selection control

### ISSUE THREAD

**Issue by yogeshvachhani** [lowcoder-org/lowcoder#229]
**Is your feature request related to a problem? Please describe.**
While trying to load 72k rows in Select control we observed that take very long time to load as all the values are fetched from database.

**Describe the solution you'd like**
In place of Select if a new component is created that will look like a simple Input Text control but it will be bound/mapped to data source and when user types something it will show a list of item which are filtered as per users entered text.

**Describe alternatives you've considered**
I think one way to achieve this would be to put a Textbox control and then when user types to run a query to fetch data based on user entered text and show the list of items from which user can select by clicking on and Item.

**Additional context**
Here is a sample screen shot of what we have been using in other low-code tools.
![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/cbc48e8a-9264-4e8c-8f97-904eb16aa880)

**Comment by FalkWolsky** [comment]
This should be actually already possible. We will check it and see if there is an easy solution possible.

**Comment by FalkWolsky** [comment]
Did you try the proposed solution way? Pleas re-open the issue when you cannot find a way with the current components.
