### ISSUE TITLE
[Bug]: Default value doesn't work in select

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When *default value* is added to a select, no value is selected by default.

### Expected Behavior

The default value should be selected.

### Steps to reproduce

1. Add select field
2. Give it a few options
3. Set the default value
4. Publish
5. Check the frontend

**Comment by FalkWolsky** [comment]
We checked it and cannot reproduce the bug you described.
The default value is taken automatically and get's displayed accordingly.
<img width="451" alt="Screenshot 2023-07-22 at 17 04 56" src="https://github.com/lowcoder-org/lowcoder/assets/3671017/2f890d0a-cde7-480e-9b29-07a9dbddbc6f">

We close for now. If you can help us to reproduce - just write here...
