### ISSUE TITLE
[Feat]: Docker documentation needs some love

### ISSUE THREAD

**Issue by LennardF1989** [lowcoder-org/lowcoder#236]
As this is a fork from Openblocks, most likely you guys did a find and replace on the documentation, because a lot of the links are broken. Eg. https://docs.lowcoder.cloud/lowcoder-documentation/setup-and-run/self-hosting has links to non-existent YAML files, the docker command does not work (uppercase in the repo name), plus you can't even pull the docker image without logging in.

**Comment by FalkWolsky** [comment]
Thank you very much for your hint! We fixed all links and need to excuse! It is right, that we ha by the time the only chance to find replace. This comes with a lot of glitches, that we step by step repair. A lot of work!

Please check again. I will mark the issue as closed, but if you find further problems on the self-host page, feel free to re-open.
