### ISSUE TITLE
[Bug]: Performance issue in Table Component when using children

### ISSUE THREAD

**Issue by LennardF1989** [lowcoder-org/lowcoder#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've discovered that when an entry in the table has an `children`-array, it will add an expand/collapse button to that row. Very neat!

However, it appears there is a significant performance issue when this feature is used. It's okay for tables with only a handful of rows. But once there is a lot to expand/collapse (my nested levels can go up to 4), the performance of the application will drop drastically.

When I show the same data as a flat list, it's pretty much a consistent performance.

I've made sure to check it's not my query or the logic before the table updates. It's not, the query runs and returns a (nested) result pretty much instantly.

### Expected Behavior

Preferably loading the data into the table is just as fast as loading the flat list. However, keeping the application responsive (so not hanging the browser rendering) should be the priority.

### Steps to reproduce

Have a big tree with lots of data. My object looks like this:
```
{
    id: 1234,
    type: "string",
    state: "string",
    parent: 1234,
    title: "string",
    priority: 1234,
    children: [], //Contains a list of this object again, up to 4 deep.
    data1: 1234,
    data2: 1234
}
```

I'd say test a very extreme scenario. I have 20 root items, each of which has about 3 childs, these have at least 20 childs each, which have about 4 childs each.

**Comment by FalkWolsky** [comment]
Generally we do not consider this as a bug and will close the issue therefore. The standard table has many features and is therefore relatively complex. Especially by the possibility of having the extension with full canvas (place another full component) per row. This already slows down - just by the immense object structures and possible combinations. A nesting of 4 levels means to multiply this effect. It is suggested to use then another component to achieve faster results - or think of another structure to represent this data...
