### ISSUE TITLE
[Bug]: Workspaces do not seem to be available

### ISSUE THREAD

**Issue by LennardF1989** [lowcoder-org/lowcoder#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The feature described [here](https://docs.lowcoder.cloud/lowcoder-documentation/workspaces-and-teamwork/workspaces) is not available in the self-hosted version created using the Docker compose file.

There is no "Create workspace" button. Also an issue on Openblocks.

### Expected Behavior

There is a "Create workspace" button.

### Steps to reproduce

Install Lowcoder, register an account, go to Workspaces.

**Comment by renekahr** [comment]
Same here.

**Comment by Skarema** [comment]
I'm also missing the button. Does anyone know how to fix this?

**Comment by LennardF1989** [comment]
Apparently this is an option that's only turned on when the application runs in SaaS mode:
https://github.com/lowcoder-org/lowcoder/blob/main/client/packages/lowcoder/src/pages/setting/organization/orgList.tsx#L148

I'll see if I can get a fix in.

**Comment by FalkWolsky** [comment]
This is actually not a Bug, but a configurable Behaviour.
The background is, that some times you want to have a Lowcoder Installation for a Team or a Company.
Here you would welcome the Workspaces a lot. However, many use cases do make sense for a singe Developer of Applications. In such cases, the Workspaces are not needed.

The ENV Variable for Docker is: WORKSPACE_MODE.
Turned to SAAS, the Workspaces will be available.

**Comment by FalkWolsky** [comment]
As we have seen, there were efforts towards an EE Version of the Lowcoder Team. However, the Team did not publish the EE Version code openly. Therefore we start all over. I understand this issue here is about Workspaces. But you may find still artifacts of code towards the Auth for different OAuth providers for example.
Frankly speaking, we still clean up.

**Comment by xolyu** [comment]
> The ENV Variable for Docker is: WORKSPACE_MODE. Turned to SAAS, the Workspaces will be available.

I have configured `WORKSPACE_MODE=SAAS` as an environment variable in Docker, for my existing instance of Lowcoder 2.0.0. Then recreated the Lowcoder all-in-one container. Unfortunately, the "Create workspace" button does not appear.

Is there anything else I need to do?

-----

When I check via `docker inspect`, I see that the environment variable is set.

```json
"Env": [
	"WORKSPACE_MODE=SAAS",
	...
],
```
