### ISSUE TITLE
Question: What is the stance on exposing some EE functionality from the original Openblocks in Lowcoder?

### ISSUE THREAD

**Issue by LennardF1989** [lowcoder-org/lowcoder#263]
Is the Lowcoder team also going to have a difference in a CE and EE version, are they going to do SaaS with paywalled features?

I feel we could turn this in a proper open-source project where there is just one version, but that a SaaS is still feasible enough to sell separately without paywalling features. It can also remove some of the complexity in the code-base.

**Comment by FalkWolsky** [comment]
Generally, we invite you to join the Discord-Server of Lowcoder to stay in sync with our Updates.
https://discord.gg/qMG9uTmAx2

The good news is this: Lowcoder-org will stay Opensource, untouched, and open to everyone as Community Edition)
We do offer Cloud Hosting with lowcoder.cloud, where the shared Community Edition (Lowcoder-org) will be available for free. Private isolated Hosting for the CE will be available, as also other managed services like Database, Chat and Integration Environments.

Next to all this, we currently develop a Lowcoder-pro Enterprise Edition. Lowcoder-pro will stay Opensource and come with its own license. It will extend Lowcoder-pro by a Plugin Mechanism, so both Repositories can develop without negative inference. The EE Version addresses stronger the needs of Enterprises and big Companies - so it will come with a modern and smart pricing system, which keeps even costs low for smaller Companies that want to jump on.

However, that does not touch the Opensource or free character of Lowcoder.
