### ISSUE TITLE
[Bug]: Unit tests for testFormRegisterSuccess, testFormLoginSuccess and testRegisterFailByLoginIdExist fail

### ISSUE THREAD

**Issue by LennardF1989** [lowcoder-org/lowcoder#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

These tests will register and login an user and test the resulting objects accordingly.

There are two mistakes at play here:
- The `application.yml` has no `common.cookie-name`. This will make the tests fail no matter what. Add the following to the file located in the test resources:
```yaml
common:
  cookie-name: UT-TACO-TOKEN
```
The name has to be UT-TACO-TOKEN!
- After fixing the cookie mistakes, both testFormRegisterSuccess and testFormLoginSuccess  trip over the line: `assertEquals(1, connection.getOrgIds().size())`. Either the logic of the test is wrong or the logic of the application itself, but no matter if you set Enterprise-mode in the `application.yaml`, a domain is never assigned to the auth requests in these tests, resulting in a connection not being related to an organisation. Removing both lines makes the test succeed, but this might be sticking your head in the sand. Needs checking.

### Expected Behavior

All tests succeed.

### Steps to reproduce

See above.

**Comment by FalkWolsky** [comment]
I think this part will get rewritten as a whole. (Followed by the efforts for EE Version)
