### ISSUE TITLE
WORKSPACE_MODE turned to SAAS, Workspaces still not available.

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#282]
> The ENV Variable for Docker is: WORKSPACE_MODE. Turned to SAAS, the Workspaces will be available.

I have configured `WORKSPACE_MODE=SAAS` as an environment variable in Docker, for my existing instance of Lowcoder 2.0.0. Then recreated the Lowcoder all-in-one container. Unfortunately, the "Create workspace" button does not appear.

Is there anything else I need to do?

-----

When I check via `docker inspect`, I see that the environment variable is set.

```json
"Env": [
	"WORKSPACE_MODE=SAAS",
	...
],
```

_Originally posted by @xolyu in https://github.com/lowcoder-org/lowcoder/issues/260#issuecomment-1627448423_

**Comment by FalkWolsky** [comment]
As we did test this by ourselves, I can ensure you that it works fine. Now we just need to find out what is different in your setup. Can you please use "COMMON_WORKSPACE_MODE" and tell me if you succeed?

**Comment by FalkWolsky** [comment]
We will do 2 things. First, we will work further on the naming ad harmonization of the ENV variables to have everything as clear as possible. Also, we will document changes faster.

**Comment by xolyu** [comment]
I can confirm that it works with the environment variable `COMMON_WORKSPACE_MODE=SAAS`.

Thank you very much for your support.
