### ISSUE TITLE
[Bug]:Project cannot run in Chinese environment

### ISSUE THREAD

**Issue by mousheng** [lowcoder-org/lowcoder#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

not work

### Expected Behavior

 Web Page Blank

### Steps to reproduce

1、Start a local backend server
2、install dependencies 
3、run API_PROXY_TARGET=http://localhost:3000/ yarn start
but not work

### Environment

in chinese language environment

### Additional Information

bug in Translator,some key in en.ts but not in zh.ts

**Comment by FalkWolsky** [comment]
API_PROXY_TARGET you use, when you build and run the /client by yourself.
In this case, you would use the API-Service and Node-Service independently from the client. Then you would indeed need to set the API_PROXY_TARGET. However, if you use the single docker image as you did, then it contains all inside - and no need for further configuration.

API_PROXY_TARGET=http://localhost:3000/  leads into blank screen, cause the API is delivered inside the docker as http://localhost:8080 but the frontend as http://localhost:3000
