### ISSUE TITLE
[Bug]: JSON Editor not showing all data.

### ISSUE THREAD

**Issue by yomapi** [lowcoder-org/lowcoder#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Current State
I'v assigned a array that have more than 200 items.
Problem: Not showing all data.

<img width="447" alt="스크린샷 2023-07-18 오후 3 47 41" src="https://github.com/lowcoder-org/lowcoder/assets/59224328/f5c74a21-400c-4ac9-b3d8-9e8a88fdddfc">

### Expected Behavior

Assign data to JSON Editor, and display all data without any problem

### Steps to reproduce

1. Unzip the test.json.zip file
2. import app by using test.json
3. browse "test.csv" file using "browse button"
4. Json Editor not showing all data

NOTE: There is some JS script at file upload button's on change event handler

[app: test.json.zip](https://github.com/lowcoder-org/lowcoder/files/12077545/test.json.zip)
[test.csv](https://github.com/lowcoder-org/lowcoder/files/12077567/test.csv)

### Environment

Self Host on EC2 using Docker all in one image
Instance type: t3.medium
OS: Ubuntu

#### 1. Validate Data
The data I put into the JSON Editor is as follows:
```
[
  {
    "chapterName": "9까지의 수",
    "conceptId": "416",
    "preRequisiteChapterName": "",
    "preRequisiteConceptId": ""
  },
  {
    "chapterName": "여러 가지 모양(1)",
    "conceptId": "417",
    "preRequisiteChapterName": "",
    "preRequisiteConceptId": ""
  },
  {
    "chapterName": "덧셈과 뺄셈(1)",
    "conceptId": "418",
    "preRequisiteConceptId": "416",
    "preRequisiteChapterName": ""
  },
  {
    "chapterName": "비교하기",
    "conceptId": "419",
    "preRequisiteChapterName": "",
    "preRequisiteConceptId": ""
  },
  ...more data folow
]
```
I have assigned the same data to the JSON Explorer, and I have confirmed that there is no issue with the JSON data.
<img width="413" alt="스크린샷 2023-07-18 오후 3 51 31" src="https://github.com/lowcoder-org/lowcoder/assets/59224328/63904457-78f0-4011-ba0a-6806419464fb">

## 2. see console to get any error message
There was nothing useful at console.

## Questions
Is there a limit to the number of items that can be placed in the JSON Editor?
Do I need any additional configurations?

## summary
1. Json Editor not showing all data
2. data is fine. Confirmed by json explorer
3. Nothing useful at console
4. limit to the number of items? or Need additional configurations?

thanks for help

**Comment by aaron1604** [comment]
Hey @yomapi 

It seems to be working and showing all the data for me. It just takes time to load a bit based on number of data. If you select an editor and try to go down, it will load it. Although, I agree the current behaviour is not so good and we will try to improve it in near future but at least it work now.

Here is the screenshot for a reference, I used the same app and csv which you provided.

<img width="756" alt="Screenshot 2023-07-18 at 7 24 45 PM" src="https://github.com/lowcoder-org/lowcoder/assets/96607998/0e442cec-7f26-4479-aa43-d811ae9c5bc7">

**Comment by mousheng** [comment]
@yomapi The problem should be solved immediately

**Comment by yomapi** [comment]
> @yomapi The problem should be solved immediately

Thank you for reminding me about this issue.

 I will forward the response in the [Discord channel message](https://discord.com/channels/1096896040159957084/1096896040650678314/1130770481168003124).

Lowcoder team is aware of the problem and is currently focusing on high-priority tasks. 
However, they have assured us that they will make efforts to fix this issue during the sprint.

Furthermore, due to personal reasons, I don't have time to dedicate to this issue.
so I am hopeful that the Lowcoder team will fix this. 

By using the zip files above, you can reproduce this issue.
How do you think about you resolving this problem and submitting a pull request?
Since this repository is open-source, after all :)

**Comment by mousheng** [comment]
I have already submitted the PR, just wait for the update. I saw that you also submitted an issue on Openblocks, but Openblocks has been abandoned and there will be no response
