### ISSUE TITLE
[Bug]: Lambda Query run failed - Cannot read properties of undefined (reading 'querytCode')

### ISSUE THREAD

**Issue by satwal** [lowcoder-org/lowcoder#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I run a query that uses the Lambda extension. I occasionally get the following error
Cannot read properties of undefined (reading 'querytCode')

I have tried to increase the timeout with no success.

### Expected Behavior

Expected ok 200 response

### Steps to reproduce

Create a new lambda query and try to run it. I have provided a screenshot of the error and lambda code
![screenshot](https://github.com/lowcoder-org/lowcoder/assets/7481985/933b2fe3-ee02-416a-81e3-e6ad06f7212c)

### Additional Information
`
import boto3
import time
import paramiko
import json

def lambda_handler(event, context):
    ec2 = boto3.client('ec2')
    s3 = boto3.client('s3')
    
    request = event["request"]
    instance_id = event['instance_id']
    username = event['username']
    password = event['password']
    
    # Download .pem file from S3 to Lambda /tmp directory
    s3.download_file($name, $file.pem, $path)
    
    if request == 'status':
        response = ec2.describe_instances(InstanceIds=[instance_id])
        instance_status = response['Reservations'][0]['Instances'][0]['State']['Name']
        
        return {
            'statusCode': 200,
            'body': 'Current instance status: {}'.format(instance_status),
            'url_sd' : '',
            'url_fs' : ''
        }
    
    elif request == 'stop':
        response = ec2.stop_instances(InstanceIds=[instance_id])
        waiter = ec2.get_waiter('instance_stopped')
        waiter.wait(InstanceIds=[instance_id])
        
        return {
            'statusCode': 200,
            'body': 'Server has stopped',
            'url_sd' : '',
            'url_fs' : ''
        }

    elif request == 'start':
        response = ec2.start_instances(InstanceIds=[instance_id])

        waiter = ec2.get_waiter('instance_running')
        waiter.wait(InstanceIds=[instance_id])
        print('instance is running: ' + str(instance_id))
        
        time.sleep(20)
        
        # Paramiko setup
        key = paramiko.RSAKey.from_private_key_file("/tmp/mykey.pem")
        ssh_client = paramiko.SSHClient()
        ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        
        # Connect to the instance
        instance_info = ec2.describe_instances(InstanceIds=[instance_id])['Reservations'][0]['Instances'][0]
        instance_dns = instance_info['PublicDnsName']
        ip = instance_info.get('PublicIpAddress', None)
        
        url_sd = "No ip is assigned"
        url_fs = "No ip is assigned"
        
        if ip is  None:
            ip = "No ip is assigned"
        else:
            url_sd = ip + ":$port1"
            url_fs = ip + ":$port2"
        
        ssh_client.connect(hostname=instance_dns, username=$username, pkey=key)
    
        # Execute the bash command
        command = f'./$script.sh {username} {password}'
        stdin, stdout, stderr = ssh_client.exec_command(command)
        
        time.sleep(60)
        
        return {
            'statusCode': 200,
            'body': 'Server has started',
            'url_sd' : url_sd,
            'url_fs' : url_fs
        }
    
    return {
            'statusCode': 200,
            'body': 'Request invalid',
            'url_sd' : '',
            'url_fs' : ''
        } 
`

**Comment by FalkWolsky** [comment]
As we made the query timeout setting (frontend) respected at the backend too (overwrite the default value dynamic), this problem should be solved (a longer time ago). It it persists, please re-open the issue!
