### ISSUE TITLE
[Bug]: Query - "Timeout After" value not utilized.

### ISSUE THREAD

**Issue by placidic** [lowcoder-org/lowcoder#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting a "Timeout After" value in any of my queries, they all timeout after 30 seconds, no matter what value is set.
![image](https://github.com/lowcoder-org/lowcoder/assets/1841459/e65c7db8-ee04-4b6c-b77c-807ce585c4d5)
![image](https://github.com/lowcoder-org/lowcoder/assets/1841459/15db5888-506e-431f-a8cf-2ec6cdf11daf)

### Expected Behavior

It's expected that the queries being invoked, would respect the "Timeout After" value defined and apply it to the HTTP call.

### Steps to reproduce

1. Create a new query object with a long running process (> 30 seconds)
2. Set the "Timeout After" setting for the query to >30 second (ex. 60 seconds)
3. Invoke Query

### Environment

Lowcoder 2.0.1

**Comment by placidic** [comment]
I further tested this issue using a long running n8n workflow to rule out a server side timeout - and validated the bug by receiving the same error outcome.

1) Created a simple webhook workflow with a 1min wait step before responding
2) Created a REST API query in lowcoder, set to a 45sec timeout
3) Manually invoked the query via button click event
4) Query fails with 504 Gateway Timeout after 30sec.

**Comment by ludomikula** [comment]
> could it be related to this old openblocks issue? [openblocks-dev/openblocks#288](https://github.com/openblocks-dev/openblocks/issues/288)

I believe this is a different issue. Default nginx proxy timeout is 60 seconds.
Here the problem is in the webclient when calling the HTTP request - it uses default timeout setting which is 30 seconds.
