### ISSUE TITLE
[Bug]: <Hidden Module is disabled in preview/view modes>

### ISSUE THREAD

**Issue by jnewman-eti** [lowcoder-org/lowcoder#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created a module to handle some common tasks across my applications, that will perform some queries and provide some output data for apps to use.  There are no UI components in this module, and it is intended to be hidden from the UI inside the apps.  When this module is hidden, in edit mode everything works as expected.  The module performs its work, executes a success event, and triggers the apps to begin performing subsequent work.  
However, in preview/view modes, the module does not perform the intended work, and the success event never fires, preventing the apps from beginning performing their work.

Due to the discrepancy between edit and view modes in this instance, it seems this behavior is not intentional.  A hidden component is not necessarily intended to be disabled, as per my understanding.

If this is intentional, how could a developer group a batch of queries/transformers/temporary state objects together that are intended to perform a specific task together, to be able to reuse this in multiple apps?

### Expected Behavior

If a module is used inside an app, and it is hidden, it should not be disabled.

### Steps to reproduce

1. Create a new module.  
2. Create some query that the module can execute on page load.  
3. Create an event to fire upon completion of the query run (not an event handler, but a module event.)
4. Add a success event handler on the query created, and on success, trigger the module event.
5. Publish the module, and add it to an app.
6. On the app module properties, in the "hidden" property, set it to "true".  The module will hide.  In edit mode, the module should trigger the event successfully.
7. Switch to preview/view mode.  The module will not execute and will not trigger the event successfully.

### Environment

Using a synced fork of the main branch.  Currently 10 commits ahead of main branch.

**Comment by FalkWolsky** [comment]
We solved this in v2.1.7. Can you please re-check it?
