### ISSUE TITLE
[Bug]: ECharts styling

### ISSUE THREAD

**Issue by Skarema** [lowcoder-org/lowcoder#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The legend and the title at ECharts are not displayed correctly.

<img width="538" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/84594421/160912da-ac69-439d-841b-75451b79dcf4">

### Expected Behavior

Display correctly.

### Steps to reproduce

1. create chart
2. add a title
3. add series with a title
4. reduce size of chart so that the legend appears behind the chart title

**Comment by raheeliftikhar5** [comment]
We believe this is resolved. Please let us know if you still face this issue. Thanks
