### ISSUE TITLE
[Bug]: Date Input Validation broken

### ISSUE THREAD

**Issue by Daniel-CS-Team** [lowcoder-org/lowcoder#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When inserting a Date component and setting the `Required field` flag, the validation is not done properly. Even after selecting a date, still the message "Required field" is displayed an the form cannot be send.

### Expected Behavior

When a value is selected, the message "Required field" should disappear and given all other inputs are valid, the form should be send.

### Steps to reproduce

Create new App
Add empty Form component
Add Date component into Form
Activate `Required field` flag on Date component
Try to fill an send the Form

### Environment

We run lowcoder on AWS ECS FARGATE. The docker iamge is Version 2.0.1

**Comment by raheeliftikhar5** [comment]
This is resolved in 2.3.2.
