### ISSUE TITLE
[Bug]: JSON Schema Form sub-objects not working

### ISSUE THREAD

**Issue by lukas-kd** [lowcoder-org/lowcoder#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If i create a json schema form with properties containing the type "array" or "object" it does not really work.

**JSON Schema has property with object:**
It get's rendered with all properties, but it looks as it would be the main object.

**JSON Schema has a list with objects:**
No option to add/edit/remove the entries.

Example Json Schema for sub-objects:

![image](https://github.com/lowcoder-org/lowcoder/assets/50477277/0c4a18a2-25be-458f-b0d7-af5968604143)

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "childs": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name"
      ]
    }
  },
  "required": [
    "id",
    "name",
    "childs"
  ]
}
```

Example Json Schema for lists with objects:

![image](https://github.com/lowcoder-org/lowcoder/assets/50477277/c20f5c6a-dae0-400c-834d-eefb0f17ab04)

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "childs": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "name",
    "childs"
  ]
}
```

### Expected Behavior

It gets rendered correctly, containing a visualization for sub-objects (like smaller font, etc...) and renders all properties of an object.
For arrays it should have add / remove buttons for entries.

### Steps to reproduce

1. Create a JSON Schema Form
2. Pase the mentiond JSON Schema

### Environment

self-hosted, podman, ubuntu 23.04

**Comment by FalkWolsky** [comment]
<img width="924" alt="Screenshot 2023-10-18 at 12 37 37" src="https://github.com/lowcoder-org/lowcoder/assets/3671017/192dbd1b-36b8-4135-b972-c817df5fb4af">

We tested it and it works as expected. We suggest you to check the JSON, UI Schema, and Default Data again.

It seems "items" need to be a JSON Object, not an Array.

Please have a look at https://jsonforms.io/examples/array

Schema:

```
{
  "type": "object",
  "properties": {
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "message": {
            "type": "string",
            "maxLength": 5
          },
          "enum": {
            "type": "string",
            "enum": [
              "foo",
              "bar"
            ]
          }
        }
      }
    }
  }
}
```

UI Schema:

```
{
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Control",
      "scope": "#/properties/comments"
    }
  ]
}
```

And Default Data:

```
{
  "comments": [
    {
      "date": "2001-09-10",
      "message": "This is an example message"
    },
    {
      "date": "2023-10-18",
      "message": "Get ready for booohay"
    }
  ]
}
```
