### ISSUE TITLE
[Feat]: Network requests for icons are sent every time a drawer or modal is opened instead of just once

### ISSUE THREAD

**Issue by the-ocean-motion** [lowcoder-org/lowcoder#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In case of using icons in some of the elements (e.g. text inputs, date, text area, ...) part of a Drawer or Modal, every time the user opens the Drawer/Modal, a network request is sent to fetch every single one of the icons. While it could be acceptable that this happens the first time that the modal is opened (e.g. lazy loading), it is then not acceptable that it happens every time the Drawer/Modal is open, as it slows down performance of the app. In cases of slow network scenarios this even causes a pause of several seconds just to open the Drawer/Modal.

### Expected Behavior

The icons should be loaded only the first time the Drawer/Modal is opened or just loaded once with the App and no longer every time the Drawer/Modal is opened.

### Steps to reproduce

1. Create a Drawer or Modal
2. Add several text input fields to it
3. Configure a prefix icon for each of the input fields
4. Add a button to the main app that opens the Drawer/Modal
5. Open the browser developer tools, in the Network tab
6. Click the button to open the Drawer/Modal and verify the network requests for each of the icons belonging to the input elements of the Drawer/Modal
7. Close the Drawer/Modal
8. Click the button again and notice that the network requests for the icons are sent again (and over and over again)
![IconsIssue](https://github.com/lowcoder-org/lowcoder/assets/18144112/e20bace4-7696-44a9-83a0-983fbc9e5d85)

### Environment

Tested on https://app.lowcoder.cloud/

**Comment by FalkWolsky** [comment]
We have this behavior not only in the drawer. It also happens on local installations with the all-in-one docker image.
We marked it as enhancement too, as the general function (icon display) does its job as expected. However, the reloading does make truly no sense and we will address it in combination with a rework on the icons. (larger icon set how it was introduced by @mousheng a while ago)

**Comment by the-ocean-motion** [comment]
Agreed, thanks a lot and I look forward to the update

**Comment by raheeliftikhar5** [comment]
Solved in v2.5
