### ISSUE TITLE
[Bug]: Component selection problem

### ISSUE THREAD

**Issue by tcfly** [lowcoder-org/lowcoder#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From right section, select `Image Editor` component, but the `Comment` component is selected
![image](https://github.com/lowcoder-org/lowcoder/assets/49434080/26c9e649-445d-41c6-b2b6-5e809ddbd4b3)

### Expected Behavior

The right component is selected

### Steps to reproduce

Step 1: select `Comment` component
Step 2: select `Image Editor` component

Please repeat the two steps if not reproduce the problem !

### Environment

https://app.lowcoder.cloud

### Additional Information

The problem exists in Data section(component panel)

**Comment by Kfelts** [comment]
I have been having this same exact problem except with "text area" and "mention." Every time I select "text area", it ends up dragging the "mention" component. I have to go back over and hold the mouse slightly above the "text area" component to select it.

**Comment by FalkWolsky** [comment]
Thank you for reporting this. Even if we work intensely every day, we was not aware of it. Naturally, we will try to fix it!
