### ISSUE TITLE
[Feat]: inline add new row in table

### ISSUE THREAD

**Issue by agaitan026** [lowcoder-org/lowcoder#442]
Hi any chance to clone something like this ? this is ms access, so at the end of each table theres always a new record empty in order to fill and if i fill it it saves to the db. Its possible with lowcode? or what you guys recommend me to do, Im recreating access app to lowcode

![image](https://github.com/lowcoder-org/lowcoder/assets/56446006/65c57728-bc68-4df7-8a86-5bf15eba000f)

**Comment by FalkWolsky** [comment]
Soon we work intensely on the table component and aim also to include this feature.

**Comment by agaitan026** [comment]
any news?

**Comment by adnanqaops** [comment]
@agaitan026 , Now, you can add Inline rows on Table. This has been implemented.
<img width="1124" alt="Screenshot 2024-12-26 at 12 57 41 PM" src="https://github.com/user-attachments/assets/e7d05ace-a644-4287-984a-298d1f29d096" />

So, closing out this ticket.
