### ISSUE TITLE
[Bug]: Mermaid Charts component error

### ISSUE THREAD

**Issue by placidic** [lowcoder-org/lowcoder#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding a new mermaid chart component, the component gets assigned an id "mermaid1" however the rendered component in editor view displays the error: "Error: Component mermaid not found."

Additionally, the component properties view fails to load:
![image](https://github.com/lowcoder-org/lowcoder/assets/1841459/b279f348-988c-4209-b617-37276215117b)

### Expected Behavior

The mermaid chart component should load upon placement with default placeholder values.
The properties for the component should render.

### Steps to reproduce

Drag a mermaid chart component to the editor window.

### Environment

Lowcoder 2.1.3

**Comment by FalkWolsky** [comment]
Please re-check with a newer version of Lowcoder. We tested it and it works. Also, we got positive feedback from other users about the function. It is the first version of the component itself, so not many settings are possible.
But the main functionality is there and does work as expected. If you find it still not working, please re-open the issue, so we can check if this is maybe a local problem?
