### ISSUE TITLE
[Bug]: Docker lowcoder-ce-frontend nginx error in latest

### ISSUE THREAD

**Issue by cripsisxyz** [lowcoder-org/lowcoder#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, 

I'm trying to run the docker of the  lowcoder-ce-frontend [(dockerhub)](https://hub.docker.com/layers/lowcoderorg/lowcoder-ce-frontend/latest/images/sha256-d234ed68a8b9d75b26f3ce7881a0f143bb1bd63f5e636209d40ecc9b838647c7?context=explore) but the container cannot run:

```
/docker-entrypoint.sh: Ignoring /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh, not executable
/docker-entrypoint.sh: Ignoring /docker-entrypoint.d/15-local-resolvers.envsh, not executable
/docker-entrypoint.sh: Ignoring /docker-entrypoint.d/20-envsubst-on-templates.sh, not executable
/docker-entrypoint.sh: Ignoring /docker-entrypoint.d/30-tune-worker-processes.sh, not executable
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/11/01 22:06:20 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
```

### Expected Behavior

There is not example of this file to mount it as a volume or is not directly included in the docker build context.

### Steps to reproduce

Using the docmentation in [the repository](https://github.com/lowcoder-org/lowcoder/blob/main/docs/self-hosting/README.md)

### Environment

local

**Comment by FalkWolsky** [comment]
Can you please re-check with the latest version of Lowcoder? We tested always and could not reproduce this behavior.
Also, which version of the Images you used when you got the error?

**Comment by cripsisxyz** [comment]
same problem with tagged versions: @FalkWolsky @ludomikula 

```
    image: "mongo:4.4"
    image: redis:7-alpine
    image: lowcoderorg/lowcoder-ce-api-service:2.1.6
    image: lowcoderorg/lowcoder-ce-node-service:2.1.6
    image: lowcoderorg/lowcoder-ce-frontend:2.1.6

```
