### ISSUE TITLE
[Bug]: Overlapping Calendar and Clear Icons in Date Range Component

### ISSUE THREAD

**Issue by yogeshvachhani** [lowcoder-org/lowcoder#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the Date Range Component show the Calendar icon by default inside the control.
When we hover it with mouse and if the date is set it also show a Clear icon but this icon shows next to the calendar icon overlapping it slightly.

Because of this it becomes a problem for user to click on the Calendar control.

![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/75c28f2c-d08a-4d6d-a5ec-873920293d57)

The Arrow Icon between the Start and End Dates is also showing up partially. This also needs to be corrected.

### Expected Behavior

Actually as the clear icon is show on hover, there should be property which allows one to either move the calendar icon to the right of the start date or there should be some way to hide.
OR
Give setting to show or hide the clear icon as per users preference.
OR
Remove the Calendar icon once a user has selected any of the date because a user can just click on any of the date to show calendar.

### Steps to reproduce

Place the DateRange component on the page.

Click on the Calendar Icon and select start & end dates.

Now hover mouse on the component.

**Comment by FalkWolsky** [comment]
We fixed this in v2.1.5.
