### ISSUE TITLE
[Bug]: Date Range Component crashes when we remove Suffix Icon

### ISSUE THREAD

**Issue by yogeshvachhani** [lowcoder-org/lowcoder#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we clear/remove the Suffix Icon in Date Range Component it crashes.

![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/c6d3f5f0-d9db-4e10-88ae-f0007cc232f4)

### Expected Behavior

It should not crash only the icon should get removed like it does in the Date Component.

### Steps to reproduce

Please a Date Range Component on page.

Locate its Suffix Icon property and click on the clear icon to remove the icon in component.

**Comment by FalkWolsky** [comment]
Thank you very much for reporting this issue. We need you kindly to excuse us and will work as fast as we can to solve it.

**Comment by FalkWolsky** [comment]
Solved in Version 2.3.1
