### ISSUE TITLE
[Bug]: Cannot delete table column within single column responsive layout

### ISSUE THREAD

**Issue by Skarema** [lowcoder-org/lowcoder#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When having a table inside of a responsive layout with one column like:
<img width="866" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/84594421/0ad08caa-0547-4a29-a69e-24a4e3102bf4">

It's not possible to delete a column of the table:
<img width="862" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/84594421/69514387-5256-42af-81a6-9972df3db762">

### Expected Behavior

Being able to delete.

### Steps to reproduce

1. add responsive layout
2. delete one column (so that there is only one left)
3. insert table into res. layout
4. add extra column
5. try to delete extra column

**Comment by FalkWolsky** [comment]
Thank you very much for reporting this issue. We will very soon fix it.

**Comment by Skarema** [comment]
FYI: With the above described setup, the error message is also shown when trying to delete an event handler on the table.

**Comment by FalkWolsky** [comment]
Yes. We have it this week on our table (desk)... Thank you for reporting!
