### ISSUE TITLE
[Feat]:we hope table widget can set column color

### ISSUE THREAD

**Issue by wengad82** [lowcoder-org/lowcoder#500]
**Is your feature request related to a problem? Please describe.**

When we use tables to display monitoring data, sometimes some numeric fields exceed the threshold, and we want to use cell color blocks to display warning colors to better view the data.

**Describe the solution you'd like**

i hope platform can set the font color or block color of the table column, but not only set the color of the table row

**Comment by FalkWolsky** [comment]
We are about to invest time to update the whole table component and make it more powerful. Colors in Columns, Grouping, a fast "Display only", better search and so on. Thank you very much for your enhancement request!

**Comment by FalkWolsky** [comment]
We implemented this now in Lowcoder v2.2.0
