### ISSUE TITLE
[Bug]: theres is no create workspace button

### ISSUE THREAD

**Issue by wengad82** [lowcoder-org/lowcoder#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Why can you see in the document that the workspace can be created, but the ce version cannot create the workspace, is this a non-CE version of the function?

the document url link as following:
https://docs.lowcoder.cloud/lowcoder-documentation/workspaces-and-teamwork/workspaces

### Expected Behavior

user can create workspace and can organizing groups access to Apps,and can organizing Apps.

### Steps to reproduce

-

### Environment

ce docker version   2.1.5-test

**Comment by FalkWolsky** [comment]
It depends on the way you install it. We have an ENV Variable, that controls the behavior.
https://github.com/lowcoder-org/lowcoder/tree/main/deploy/docker
We have an Variable "COMMON_WORKSPACE_MODE".
If you set it to "ENTERPRISE" (or if you do not set it at all), then "workspaces" are not used.
However, if you set it to SAAS, then you will see the workspaces.

**Comment by FalkWolsky** [comment]
Please try the ENV Variable. You can re-open the ticket if you find it still not working. (we did check it some minutes ago with the all-in-one docker image in /latest tag.)
