### ISSUE TITLE
[Bug]: Chart Component has stoped working

### ISSUE THREAD

**Issue by yogeshvachhani** [lowcoder-org/lowcoder#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Chart Component has stopped working after the latest update.

I have not had the time to test all other components though.

### Expected Behavior

The Chart component should work as it used to.

### Steps to reproduce

Start a new App and place Chart Component on page and the platform will not be able to load its settings or show chart.

**Comment by raheeliftikhar5** [comment]
Thanks for pointing out. We pushed a fix and believe this issue is fixed now.
