### ISSUE TITLE
[Bug]: A user registered through Keycloak is missing a username/email address and avatar

### ISSUE THREAD

**Issue by nangelov77** [lowcoder-org/lowcoder#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A user registered through Keycloak is missing a username/email address and avatar.

![keycloak-user](https://github.com/lowcoder-org/lowcoder/assets/99470328/b696450f-e96b-4895-8345-f7cb80d673c2)

### Expected Behavior

Properly display username/email address and avatar of a user registered through Keycloak.

### Steps to reproduce

1. Create a realm in Keycloak.
2. Create a client for Lowcoder in Keycloak.
3. Create a user in Keycloak.
4. Add Keycloak as OAuth provider in Lowcoder.
5. Go to the link displayed in the OAuth providers page in an incognito mode.
6. Click on `Sign up` and then on `Sign up with Keycloak`.
7. Provide your credentials and sign up.
8. Log back in as the admin user in Lowcoder and check All members page.

### Environment

Self-hosted
-------------------------
- Lowcoder v2.1.7
- Keycloak v17.0.1
- Docker v24.0.7

**Comment by FalkWolsky** [comment]
We will look into it quickly. However, we want to ask, which configuration you used?
Did you ask the right scopes? Maybe the information is not transferred by KeyCloak to Lowcoder?

**Comment by nangelov77** [comment]
Here is the configuration that I used. The scope is "openid profile email".

![Screenshot 2023-12-05 141240](https://github.com/lowcoder-org/lowcoder/assets/99470328/c4acf6dd-6a05-4e25-b4a1-f4aac1f2af30)

**Comment by FalkWolsky** [comment]
Thank you for the screenshot. We check and will fix it.

**Comment by FalkWolsky** [comment]
We did fix this now and it will be available in the upcoming release (and already in the /latest docker images)
