### ISSUE TITLE
Day.js advance format still not working

### ISSUE THREAD

**Issue by biboluke** [lowcoder-org/lowcoder#530]
<img width="1400" alt="Screenshot 2023-11-27 at 23 44 06" src="https://github.com/lowcoder-org/lowcoder/assets/23377516/f450ba51-106a-4c6d-8ec3-591e4d886899">

I'm sorry but I was not able to make it work :(
Can you help me?

_Originally posted by @biboluke in https://github.com/lowcoder-org/lowcoder/issues/445#issuecomment-1828749585_

**Comment by biboluke** [comment]
Any news? 
Unfortunately until i find a way to format the dares with ISO WEEKS it's impossible for me to update to your incredible latest updates.
Thanks

**Comment by FalkWolsky** [comment]
dayjs.format we did solve. Please have a look here: https://github.com/lowcoder-org/lowcoder/issues/445
