### ISSUE TITLE
[Feat]:Support classification for extension modules

### ISSUE THREAD

**Issue by exqmjmz** [lowcoder-org/lowcoder#537]
**Is your feature request related to a problem? Please describe.**

I have many extension modules.
There are more modules that have not been added.
The extension selection bar now has no categories.
Not easy to manage and quickly select required components.

![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/eec01f6a-ca38-49d0-8101-4518ed428ec1)
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/fc2d9acd-e1a1-4c5a-a614-3c9d92a82f58)

**Describe the solution you'd like**
Module page supports folders
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/4e4b2a59-8892-4261-8d44-5da4241a5c8c)
Fold by folder classification
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/04b725c2-3026-43c1-8bdd-97db4615e34e)

something this like:
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/3bc27bdd-5493-4375-86e9-d60ee3cf2952)

**Comment by FalkWolsky** [comment]
We agree to your finding. Also your solution seems very good. We try to add this feature soon!

**Comment by FalkWolsky** [comment]
In Version 2.3.1 we added Title, Description, Category and Icon to every App and Module.
In version 2.3.2 or latest 2.3.3 we will rework then also the module display to show folders / categories.
