### ISSUE TITLE
[Feat]:modal  for more usable space

### ISSUE THREAD

**Issue by exqmjmz** [lowcoder-org/lowcoder#556]
**Is your feature request related to a problem? Please describe.**
I found that the modal much unusable space.
Lowcoder About 40px from content area to border
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/e43c7bc4-5033-444a-aea5-09a98610d9b4)

Antd example About 20px from content area to border
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/28a68625-064e-42f3-8813-c31880646429)

**Describe the solution you'd like**
Adjust the distance from the modal content area to the border to obtain more content area.
After adjusting at the same time, the style can be more beautiful and will not leave more blank areas.

**Comment by FalkWolsky** [comment]
This is true. I think we can come up with Padding Settings to make it customizable.

**Comment by FalkWolsky** [comment]
This was realized in version 2.3.0
