### ISSUE TITLE
[Feat]:Modal and drawer support setting native titles

### ISSUE THREAD

**Issue by exqmjmz** [lowcoder-org/lowcoder#557]
**Is your feature request related to a problem? Please describe.**
Modals and drawers missing native header option.
Now add a title, you need to add it through the text component. The style is not beautiful and the page effect looks strange.

antd example:
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/e362ec0b-00a5-45f0-9325-974e8b24a7cb)
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/00c0fa24-df50-4705-b64f-85120189478d)

LOWCODER now:
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/be3b356f-7e7a-4284-aaa3-f8483a57df3a)
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/a4b318b6-a9ee-4ef4-bc14-09a3dac1ef33)

LOWCODER after:
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/6364eeba-0a11-4063-bcb5-8a201370b19b)
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/f367e3fc-f954-4f40-9406-3550a6503280)

**Describe the solution you'd like**
Modal and drawer it is best to add the original title style the same as antd example

**Comment by FalkWolsky** [comment]
It will be solved with v2.4.1 in around one week to release. Please excuse that it took us soo long!
