### ISSUE TITLE
[Feat]:Query management can support sub-folder management

### ISSUE THREAD

**Issue by ljm000** [lowcoder-org/lowcoder#558]
**Is your feature request related to a problem? Please describe.**
As a result, after there are too many query rules, management is confusing and cannot be classified.
In a normal enterprise application, there will be many types of queries, corresponding to different functions or applications.

lowcoder now
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/5ae688fa-8c20-4caa-b6e7-a3dc7fd9ba15)

**Describe the solution you'd like**
The query in the application editor can set the folder. This is a good design.
![image](https://github.com/lowcoder-org/lowcoder/assets/12406935/92e7bcd0-b443-4574-8ad2-a7359ef57b46)
System query management can be like the query management settings folder in the application editor

**Comment by FalkWolsky** [comment]
The idea is valid. There is already an Issue for it.
We will come up with this soon.
https://github.com/lowcoder-org/lowcoder/issues/256
