### ISSUE TITLE
[Bug]: Import plugins doc is wrong, feature not exist

### ISSUE THREAD

**Issue by linonetwo** [lowcoder-org/lowcoder#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://docs.lowcoder.cloud/lowcoder-documentation/lowcoder-extension/develop-ui-components-for-apps#import-plugins

### Expected Behavior

In the Lowcoder app, click Insert > Extensions > Add npm plugin in the right pane. 

Then I can input a localhost URL or remote url.

### Steps to reproduce

In the Lowcoder app, click Insert ... where is Insert? And where is the "right pane"?

### Environment

I'm evaluating using helm chart, install on a microk8s, following the doc.

### Additional Information

Or is there a way to mount custom UI component using volume? Where should I mount?

**Comment by FalkWolsky** [comment]
<img width="1188" alt="Screenshot 2023-12-04 at 16 26 09" src="https://github.com/lowcoder-org/lowcoder/assets/3671017/16cddc2a-6484-43c5-9964-bce8f20023cf">

We think you mean this functionality. It may be a bit hidden and we need to add more screenshots in the Documentation.
But the functionality is certainly existing...

**Comment by linonetwo** [comment]
Thanks, I thought the custom UI component is global accessable in a workspace, but now it seems each page has its own set of custom UI component to load.

The design is reasonable in some ways, I just didn't get it yesterday.
