### ISSUE TITLE
[Bug]: Text Component Border

### ISSUE THREAD

**Issue by meong1234** [lowcoder-org/lowcoder#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In version 2.2, there are new style attributes for Text Component which break existing UI

before update
<img width="309" alt="Screenshot 2023-12-05 at 10 54 06" src="https://github.com/lowcoder-org/lowcoder/assets/12998588/e9d0195d-7196-4164-a11f-d7c991fcda7e">

after change
<img width="414" alt="Screenshot 2023-12-05 at 10 53 31" src="https://github.com/lowcoder-org/lowcoder/assets/12998588/9d314612-65b9-4a30-9fc0-0674707b5289">

### Expected Behavior

default Text Component style for border with should be 0

### Steps to reproduce

1. have existing UI, export to JSON
2. import json

**Comment by FalkWolsky** [comment]
Solved in current /dev. Should be part of /latest container by tonight and in the update v.2.2.1 in the next days.
Please excuse!
