### ISSUE TITLE
build all in one docker image failed

### ISSUE THREAD

**Issue by wengad82** [lowcoder-org/lowcoder#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i run to build docker images command under centos 7.8

DOCKER_BUILDKIT=1 docker build -f deploy/docker/Dockerfile -t lowcoderorg/lowcoder-ce .

but same error as following
![image](https://github.com/lowcoder-org/lowcoder/assets/19250813/9a92fb5f-a4d7-4677-b3da-7b47fe82e17f)
176.9 ➤ YN0066: │ typescript@patch:typescript@npm%3A4.9.5#~builtin<compat/typescript>::version=4.9.5&hash=701156: Cannot apply hunk #8
206.4 ➤ YN0000: └ Completed in 3m 23s
206.4 ➤ YN0000: Failed with errors in 3m 24s
------
Dockerfile:129
--------------------
 127 |     COPY ./client /lowcoder-client
 128 |     WORKDIR /lowcoder-client
 129 | >>> RUN yarn --immutable
 130 |
 131 |     # curl is required for yarn build to succeed, because it calls it while building client
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn --immutable" did not complete successfully: exit code: 1
[root@mail lowcoder]#
Network error: Software caused connection abort

### Expected Behavior

can build image success

### Steps to reproduce

[root@mail data]# docker -v
Docker version 24.0.7, build afdd53b
[root@mail data]# docker-compose -v
Docker Compose version v2.23.3

clone the project 
checkout 2.2.0 as head 

the project under /home/lowcoder

cd /home/lowcoder
DOCKER_BUILDKIT=1 docker build -f deploy/docker/Dockerfile -t lowcoderorg/lowcoder-ce .

then it failed!

### Environment

centos 7.8

**Comment by FalkWolsky** [comment]
Unfortunately, it seems not to belong to Lowcoder itself. Node and CentOs have trouble as by our knowledge.
Did you try to build under another OS?
