### ISSUE TITLE
[Feat]: Content of Links Column Only Shows 3 Items

### ISSUE THREAD

**Issue by zuroma999** [lowcoder-org/lowcoder#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No matter how wide a Links column in a table is made, the content doesn't fill the width. It always only shows 3 items and then an ellipses and the rest.
<img width="524" alt="Screenshot 2023-12-14 at 1 31 09 PM" src="https://github.com/lowcoder-org/lowcoder/assets/49953523/110546b0-0ebe-4dca-a98a-4bc03e53e1d8">

### Expected Behavior

The content should expand the width of the column, to meet the expected usability of this column type.

### Steps to reproduce

Create a table with a links column, add more than three links within it, set the width of the column to a fixed pixel width to make it wide, and then and see that it always only shows 3 links.

### Environment

Mac M1, Docker, Lowcoder 2.2.0

**Comment by FalkWolsky** [comment]
We agree and found this also not optimal. As the basic function is not disturbed (users can use more than 3 Links f.w.), we see it as enhancement and will work on the ability to control the behavior. Thank you very much for reporting the issue!

**Comment by FalkWolsky** [comment]
We fixed it with v2.3.0.
Thank you for your patience!
