### ISSUE TITLE
[Bug]: Cannot access overflow menu of Data Queries if name is too long

### ISSUE THREAD

**Issue by superlaser97** [lowcoder-org/lowcoder#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot](https://github.com/lowcoder-org/lowcoder/assets/16456961/906ce44b-7610-4c8f-bbf6-4535c88ecd5f)

If name of the item is too long, the overflow menu and edit icon will not appear.

### Expected Behavior

The overflow menu and pen icon should not be affected by the long item name

### Steps to reproduce

Create an item with name that exceeds the width of the list

### Environment

Docker compose, all in one image

**Comment by FalkWolsky** [comment]
We agree and know this behavior. It is a bit annoying. True. We will fix it as soon as possible while we work on the general Data Query Dialogue extension. Please have a bit of patience with us, as a general system update, Table and other areas are of higher priority. We think to solve this topic in January.

**Comment by FalkWolsky** [comment]
We did fix it now.
