### ISSUE TITLE
[Bug]: Table Column Regeneration not refreshing columns from updated dataset

### ISSUE THREAD

**Issue by placidic** [lowcoder-org/lowcoder#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a table who's data is bound to the result of a SQL query. When I remove columns from my dataset, and rerun the data query,, I am notified that the data has changed and to click the refresh icon to regenerate the columns:
![image](https://github.com/lowcoder-org/lowcoder/assets/1841459/65d2f77a-9443-4532-b4a3-82d2078bc9cc)
However when I click the refresh button, nothing happens and the old columns remain.

### Expected Behavior

The table columns should update to remove columns that no longer exist in the executed dataset.

### Steps to reproduce

1. Create a Query that returns 3 columns
2. Bind the Query.data to the table data property
3. Update Query to remove a column
4. Click Refresh on the Table column designer section

### Environment

Lowcoder v2.2.1
Openshift / AWS hosted

**Comment by renekahr** [comment]
Confirm. Same for me.

**Comment by FalkWolsky** [comment]
We solved it and publish it with the upcoming release
