### ISSUE TITLE
[Bug]: Divider not rendering unless label contains text.

### ISSUE THREAD

**Issue by placidic** [lowcoder-org/lowcoder#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding a divider component to the screen, it no longer appears on the rendered page unless a title is applied:
![image](https://github.com/lowcoder-org/lowcoder/assets/1841459/2a76e323-1386-44c7-81a0-3278382d7213)
![image](https://github.com/lowcoder-org/lowcoder/assets/1841459/c8a69c30-2978-45e6-9345-84c5d0ccfae1)

With Titles:
![image](https://github.com/lowcoder-org/lowcoder/assets/1841459/0ad1bda5-d677-4a74-924c-0d25024ca56d)

### Expected Behavior

I would expect the divider to still render with no nested text.

### Steps to reproduce

1.Add a divider to the canvas without a title.
2.Preview

### Environment

Lowcoder 2.2.1
Openshift/K8

**Comment by renekahr** [comment]
Can you check the border width? I believe with the last update, the border width of the divider has been set to 0px by default. Which is of course not ideal.

**Comment by FalkWolsky** [comment]
In the chat on Discord we found together the solution. As we introduced now free control of Boder-Width - one have to set it > 0px here to see anything. While this is logical on on side, we will still enhance the component to show "default" at least 1 pixel width.
