### ISSUE TITLE
[Bug]: Table page size dropdown appears behind fixed table elements

### ISSUE THREAD

**Issue by placidic** [lowcoder-org/lowcoder#596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a table component is used, along with the Page Size Selector, any "fixed" elements of the table, are appearing on TOP of the Page Selection dropdown.  This has been confirmed on both fixed headers, as well as fixed columns:

![image](https://github.com/lowcoder-org/lowcoder/assets/1841459/8b8b8ca7-6ad4-4a07-a667-26a2c9d06f76)

### Expected Behavior

It would be expected that the Page Selection dropdown have a higher z-index than the fixed elements so that it layers correctly on the screen.

### Steps to reproduce

1. Add a table component with the page size selector enabled.
2. Enable Fixed Header option
3. Open page size selector drop down

### Environment

Lowcoder 2.2.1
Openshift / K8

**Comment by renekahr** [comment]
Confirm. Same for me.

**Comment by FalkWolsky** [comment]
Actually, this is not a bug - but in this case truly a feature. Please find in the layout properties of the table the possibility to "fix header" and "fix toolbar" individually. If you do not fix the toolbar - it will (and should) scroll away on a "fixed height" table.
