### ISSUE TITLE
[Bug]: Table column disappearing

### ISSUE THREAD

**Issue by superlaser97** [lowcoder-org/lowcoder#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I resize a table column that is not the last column and make the table go pass 100% width, the last column disappears.

Below is a recording for Firefox on Android

https://github.com/lowcoder-org/lowcoder/assets/16456961/677f9f12-ce15-4751-afb8-a1ae71a2292e

### Expected Behavior

Last table column should be visible even if the table is resized beyond 100% width

### Steps to reproduce

Create a table and increase the width of any columns except the last column, and make the table go beyond 100% width. When scrolling the table horizontally to the right side, the last column is not visible

### Environment

Docker lowcoder-ce:2.2.1
Firefox v121 on Android, Windows, Linux
Webkit v17 on iOS

### Additional Information

Only occurs on Firefox and Webkit. No issues with Chrome

**Comment by iamabhshk** [comment]
@superlaser97 Can I look into this issue?

**Comment by superlaser97** [comment]
> @superlaser97 Can I look into this issue?

Sure, I can help you with whatever you need. I also updated the report to include website, as it also has similar behavior. I also found a workaround which is to add an empty column at the right.

**Comment by FalkWolsky** [comment]
Thank you very much for the video! That helps truly to understand the effect and bug.
Please excuse the bug itself! We will start working on it directly.

**Comment by FalkWolsky** [comment]
This seems fixed now
