### ISSUE TITLE
[Bug]: <title>when SQL query change select column,and refresh table widget column,but doesn't action

### ISSUE THREAD

**Issue by wengad82** [lowcoder-org/lowcoder#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I bind  a SQL QUERY to  a table widiget ,when i add a SQL SELECT  column or change the SQL, then run the SQL,but when i click refresh button to refresh table column,but the columns list doesn't change!

### Expected Behavior

when change the sql,then fresh table widget column list,it can change to add new column or delete old column.

### Steps to reproduce

1. add a table widget to app
2. create a sql query  ,such as "select stuname,stu_id from student"  ,and run it ,it work well
3. bind the sql query to the table,the table work well.
4. then change to SQL as "select stuname,stu_id,stuaaa from student",and run it ,it work well
5. click to table widget fresh button to refresh the column,it doesn't change to the new column list!

**Comment by FalkWolsky** [comment]
This is a bug for which another issue was already created. It will be solved in the current version release in some days.
You can test already with the /latest images
