### ISSUE TITLE
[Feat]: Table Enhancement: Support for currentRow/currentCell in Hide Function

### ISSUE THREAD

**Issue by meong1234** [lowcoder-org/lowcoder#627]
**Is your feature request related to a problem? Please describe.**
Add support for `currentRow` and `currentCell` in the Hide function. This will allow dynamic visibility control in user interfaces, based on the data in the current row or cell.

**Describe the solution you'd like**
I propose enhancing the Hide function to accept currentRow or currentCell as parameters. This enhancement would allow developers to create more dynamic, context-aware user interfaces. For example, certain buttons or options could be hidden or shown depending on the data in the current row or cell, enhancing the overall user experience and allowing for more customized interactions.

**Additional context**
<img width="281" alt="Screenshot 2024-01-12 at 11 37 23" src="https://github.com/lowcoder-org/lowcoder/assets/12998588/aa18309d-7524-43d1-830f-46e779e9cde9">

**Comment by FalkWolsky** [comment]
As we do have a hide option on the column itself, it is sufficient already. Or?

<img width="761" alt="Screenshot 2024-01-12 at 14 03 23" src="https://github.com/lowcoder-org/lowcoder/assets/3671017/85c69431-e96f-4851-a828-5ecde5d29934">

Please re-open and give more context, how your proposed solution solves the idea better...

**Comment by meong1234** [comment]
hi @FalkWolsky , 

To clarify my earlier point, the problem arises due to the variables "currentCell" or "currentRow" being undefined within the column hide function.

Let me elaborate on the use case: the goal is to dynamically control the visibility of certain columns based on the value of a specific field in a row. 

For instance, consider table contain **customer.type**, **customer.organization**  field. 
- When the **customer.type is "B2C"**, the requirement is to **hide** the **'organization'** column. 
- Conversely, if **customer.type is *"B2B", the 'organization'** column should be displayed.

I hope this explanation makes the scenario clearer, and I look forward to any suggestions or solutions you might have.
