### ISSUE TITLE
[Bug]: Custom component is not displaying anything

### ISSUE THREAD

**Issue by vasileermicioi** [lowcoder-org/lowcoder#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

adding a Custom component in editor displays nothing, just a white background
![image](https://github.com/lowcoder-org/lowcoder/assets/45198547/34e4bc37-a2fb-4ecf-8e81-6d1b5f66dd2e)

### Expected Behavior

To see a button and a text with current user info

### Steps to reproduce

New App -> Integrations & Extensions -> Custom component

### Environment

Windows 10, Chrome Version 120.0.6099.201 (Official Build) (64-bit)

### Additional Information

https://app.lowcoder.cloud/apps/65a2b885fb433e0f70c8b153

**Comment by FalkWolsky** [comment]
This belongs to the Update of many Library versions and we need kindly to excuse.
We will make sure it runs in the upcoming Release!

**Comment by vasileermicioi** [comment]
I confirm it is fixed.
I am also interested in https://github.com/lowcoder-org/lowcoder/issues/639, 
as this puts Lowcoder in another league compared to the other I tried like Illa, ToolJet, AppSmith, BudiBase
