### ISSUE TITLE
[Bug]: Cannot fire notification when embled SDK into react app

### ISSUE THREAD

**Issue by thedang** [lowcoder-org/lowcoder#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
When i create app module at your lower cloud, and i want embbed into my react app.
Every thing work well, expect notification , has error when show notification

![image_2024_01_16T08_29_29_276Z](https://github.com/lowcoder-org/lowcoder/assets/8512497/841e9d00-3632-45e9-a358-307fe149efec)

https://drive.google.com/file/d/17rMhbjkrNeuv9--QUEkRapU49qpTDmR2/view?usp=sharing

Here my error and sourcecode when i embbed app into react app.

`import './App.css';
import { LowcoderAppView } from "lowcoder-sdk";

function MyExistingAppPage() {
  return (
    <div>
      <LowcoderAppView appId="65a6266e5ad33e16b574095c"/>;
    </div>
  );
}

export default MyExistingAppPage;`

### Expected Behavior

Dont show error when use notification in low coder when embedded in react app or angular app.

### Steps to reproduce

Please fix

**Comment by FalkWolsky** [comment]
We have to look into it. Please mind, that we changed from React 17 > React 18.
That means, that render is now differently executed / programmed. Maybe it has to do with it.
https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis

**Comment by thedang** [comment]
Ok , thanks @FalkWolsky

**Comment by FalkWolsky** [comment]
It was a bug and will be solved with Version 2.3.2. Please excuse, that it took us so long!

**Comment by raheeliftikhar5** [comment]
This is resolved now.
