### ISSUE TITLE
[Feat]: Better QR/Barcode scanner library

### ISSUE THREAD

**Issue by superlaser97** [lowcoder-org/lowcoder#660]
**Is your feature request related to a problem? Please describe.**
Scanner is unreliable when using it to scan any barcode or QR code. One of the developers mentioned it was due to the free library that was used.

**Describe the solution you'd like**
Integrate a better library for QR/Barcode scanning with https://github.com/mebjas/html5-qrcode

**Describe alternatives you've considered**
I tried to import the library and build a custom component, but it failed to import as does not meet one of the restriction requirements in https://docs.lowcoder.cloud/lowcoder-documentation/lowcoder-extension/use-third-party-libraries-in-apps

**Additional context**
Discussion thread on Discord for more context 
https://discordapp.com/channels/1096896040159957084/1184794120712110100

**Comment by FalkWolsky** [comment]
We implemented it as Component-Plugin, so you can already start to use it.

[html5-qrcode Component Plugin on NPM.js](https://www.npmjs.com/package/lowcoder-comp-qrcode-scanapp)
