### ISSUE TITLE
[Bug]: Event Handlers in Dropdown do not read current item variable correctly

### ISSUE THREAD

**Issue by decaller** [lowcoder-org/lowcoder#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/lowcoder-org/lowcoder/assets/4971396/71c4876b-d3c5-48bf-b3dc-d7c64018c0db

As the video shows, a bug happens when you set the event handler with a current item variable resulting calling the first variable everytime

### Expected Behavior

the second and next iteration should recall the second and next item in the list

### Steps to reproduce

![image](https://github.com/lowcoder-org/lowcoder/assets/4971396/ae63857f-7a22-46ff-a917-c60a37cfeef3)

### Environment

https://app.lowcoder.cloud/apps/65b75804fb433e0f70c95dad/view

### Additional Information

already post on discord https://discord.com/channels/1096896040159957084/1201434760782815272

**Comment by raheeliftikhar5** [comment]
This is resolved.
