### ISSUE TITLE
[Bug]: List View doesn't expose component updates for text inputs

### ISSUE THREAD

**Issue by international-omelette** [lowcoder-org/lowcoder#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I put an input component inside a list view, the `items` property of the list view should reflect the current values of all components inside it. However, this doesn't work for text input fields with a default value. 

### Expected Behavior

The `item` propery of the list view should reflec current data of all component types

### Steps to reproduce

Attached app config
[Listview_Items_Value_Access.json](https://github.com/lowcoder-org/lowcoder/files/14113402/Listview_Items_Value_Access.json)

### Environment

2.3.0

**Comment by FalkWolsky** [comment]
Solved in Version 2.3.1

**Comment by FalkWolsky** [comment]
Solved in Version 2.3.1
