### ISSUE TITLE
[Bug]: Custom validation is one step behind

### ISSUE THREAD

**Issue by international-omelette** [lowcoder-org/lowcoder#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I put a custom validation expression into a text component, the validation checks the last value and not the current value. 

### Expected Behavior

The validation should check on the actual current value of a text component

### Steps to reproduce

https://github.com/lowcoder-org/lowcoder/assets/158296939/8e98e957-a88c-4781-94b5-3ab1bdbca46f

### Environment

2.3.0

**Comment by FalkWolsky** [comment]
Solved in Version 2.3.1
