### ISSUE TITLE
[Bug]: autocomplete component does not resize like textfield

### ISSUE THREAD

**Issue by support-tt** [lowcoder-org/lowcoder#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The autocomplete component does not resize like other components like textfield or number fileld.
Image (left is textfield right autocomplete)
![image](https://github.com/lowcoder-org/lowcoder/assets/61587422/9e58c119-7ce7-49a8-baa6-6f4b0a9c4634)

### Expected Behavior

The component should automatically resize like the other components

### Steps to reproduce

just add a autocomplete and resize it with the mouse.

**Comment by FalkWolsky** [comment]
Solved in Version 2.3.1
