### ISSUE TITLE
[Feat]: make ?template=false an app setting

### ISSUE THREAD

**Issue by international-omelette** [lowcoder-org/lowcoder#685]
**Is your feature request related to a problem? Please describe.**
Especially in apps that are publicly accessible, I‘d like to be able to hide the top bar by default so that it wouldn’t appear, even when theres no template parameter in the url query. 

**Describe the solution you'd like**
A switch in the app settings called „Always hide top bar“

**Comment by FalkWolsky** [comment]
We will rework a lot for app publishing. Semantic versioning, URL slugs and more.
Also, we will as you say make this setting an app publishing setting.

**Comment by FalkWolsky** [comment]
We added this in v2.4.0. Thank you for your patience and to report it here!
