### ISSUE TITLE
[Bug]: Value of select component get not updated

### ISSUE THREAD

**Issue by der-berni** [lowcoder-org/lowcoder#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created a select component from a sql query or mapped the data from an array.
The value is not changed. Not even in the preview.
![Animation](https://github.com/lowcoder-org/lowcoder/assets/5528912/e6fe7e23-644d-4da3-b5c7-19485d239b53)

### Expected Behavior

The value schuld be changed. In the Playground it work like expected.
https://app.lowcoder.cloud/playground/select/1

![Animation](https://github.com/lowcoder-org/lowcoder/assets/5528912/565eaabb-870a-45fe-8c7f-b326ed9a4725)

### Steps to reproduce

Create a select component with "Map" and Data: `[{id:0,name:test0},{id:1,name:test1}]`

### Environment

lowcoder running in docker with: lowcoderorg/lowcoder-ce-frontend:latest
Version: 2.3.0-#92196587

**Comment by yofriadi** [comment]
not sure, but there is change lately in this component regarding how it update it's value [here](https://github.com/lowcoder-org/lowcoder/pull/675/files#diff-a6fc2fa2ca45248f4a97c6fe7f24e87653f383ec76a549f62afcdecf2d7fd2d0R46)

**Comment by superlaser97** [comment]
I am having the same issue, the select.value is not updated. All my apps using this component broke

<img width="348" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/16456961/1fe8e5e9-e9e7-4e9e-805d-93745e7f1c10">

**Comment by dizzy-duality** [comment]
Can confirm the same on the latest dockers (front/node/api) service on google cloud-run

**Comment by FalkWolsky** [comment]
We think to close this issue as for now. Or did we wrong and it remains a pressing issue for you? In case yes, please re-open the issue again.
