### ISSUE TITLE
[Bug]: form.setData() broken in 2.3.1

### ISSUE THREAD

**Issue by Daniel-CS-Team** [lowcoder-org/lowcoder#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Is Using an Event to set the initial data of a form, nothing happens.

### Expected Behavior

The form should be populated with the data

### Steps to reproduce

Create a form with some inputs. 
Create a matching table.
Add an On Click Event Handler to the table with the action to use setData on the form to set the data to the selected row

### Environment

Self-Hosted Docker with Image 2.3.1

### Additional Information

This works just fine in Version 2.3.0

**Comment by FalkWolsky** [comment]
We think there may be a mistake in the app. Cause the functionality is working as expected. 
[Form setData by Query.json](https://github.com/lowcoder-org/lowcoder/files/14448320/Form.setData.by.Query.json)
Please find the attached app. A Form must have the form elements and the names must match.
You see, that we do set the "form field names" like "text_input" - and in the Query - we must then exactly "name" this fields.
Then it works as expected.

**Comment by FalkWolsky** [comment]
We tested it on app.lowcoder.cloud, where the most current version 2.3.1 is installed and in use.
However, if you find that it still does not work - please re-open the issue, so we can research further what is the cause.
