### ISSUE TITLE
[Bug]: Cannot upload file to S3

### ISSUE THREAD

**Issue by florentin-a-p** [lowcoder-org/lowcoder#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was using Openblock's S3 File Upload feature to upload a file of size 18MB. However, I got the following
<img width="609" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/52971362/a5a2bb32-552f-4af0-9762-d45dd2423547">

I tried uploading another file of size 10MB and it was successful. However this doesn't make sense because according to my Openblock config, my previous file size is still below 20MB.

My Openblock is set with the following config
```
LOWCODER_MAX_REQUEST_SIZE: 20m
LOWCODER_MAX_QUERY_TIMEOUT: 120
```

Here is the details of the failed file upload (18MB)
<img width="992" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/52971362/e494b3d1-78df-419d-9545-458b932567b1">

Here is the details of the successful file upload (10MB)
<img width="958" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/52971362/64ead578-775b-4a46-9180-f8d3abfef244">

### Expected Behavior

I would be able to upload a file to S3 as long as the file size is below the max limit set by the config

### Steps to reproduce

**1. Connect a data source to S3 bucket** 
<img width="407" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/52971362/7f42312f-cfce-41a3-8158-6961c8925900">

**2. Create a file upload button and choose S3 as the data source. Connect it to the previously created S3 bucket** 
<img width="213" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/52971362/c2c77fbe-b1bc-4bcd-916f-9b3415f00cb2">

**3. upload a file with size 18MB**

### Environment

lowcoder running in docker with

lowcoderorg/lowcoder-ce-api-service:2.2.1
lowcoderorg/lowcoder-ce-node-service:2.2.1
lowcoderorg/lowcoder-ce-frontend:2.2.1

**Comment by FalkWolsky** [comment]
Actually, we may run into an "effect" here, which is to check.
What does happen with the FileUpload: As soon as you "upload the file", it gets transformed in the browser first - to Base64 expression. This is not a gzipped or compacted format, so your initial File Size on Disk can be ... 18MB, but as Base64, it can be, for example, 21MB

Did you check these circumstances? Please take a moment and create a Base64 representation of your file and tell the size. Also, please just check to increase the LOWCODER_MAX_REQUEST_SIZE to for example 30MB... 

And... Lowcoder ;-))) Not so much OpenBlock

**Comment by FalkWolsky** [comment]
Please re-open if you still find the behaviour wrong..
