### ISSUE TITLE
[Style]: The default style of the form component does not comply with the Ant Design specification.

### ISSUE THREAD

**Issue by cnelf** [lowcoder-org/lowcoder#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I noticed that in the new version, custom styles have been added to some components, causing their default styles not to display correctly in the form container.
![Snipaste_2024-03-07_10-49-02](https://github.com/lowcoder-org/lowcoder/assets/42031617/f169b8ed-0460-4d24-8129-8ccef4913184)

Can be displayed correctly in the JSON SCHEMA FORM component.
![Snipaste_2024-03-07_10-50-16](https://github.com/lowcoder-org/lowcoder/assets/42031617/78e17d18-fd2c-4c3b-a39a-d869c2b2d916)

### Expected Behavior

The style of the form component can be displayed correctly.

### Steps to reproduce

STEP: Drag the component into the FORM container.

**Comment by FalkWolsky** [comment]
We agree. The extension of the Styles is an important feature. Same time it is a challenge to "keep the old styling". We have nevertheless to work on. Agreed!

**Comment by FalkWolsky** [comment]
We solved this in v2.4.0. Thank you for your patience and to report it here!
