### ISSUE TITLE
[Feat]:hope add the steps widget

### ISSUE THREAD

**Issue by wengad82** [lowcoder-org/lowcoder#753]
**Is your feature request related to a problem? Please describe.**

sometime we do somethings step by step,and the antd steps widget is more useful.

**Describe the solution you'd like**

add the steps widget to lowcoder,make the platform more powerful
you can refer as following url link resource:
https://ant-design.antgroup.com/components/steps-cn?from=msidevs.net

**Comment by FalkWolsky** [comment]
We added this in v2.4.0. Thank you for your patience!
