### ISSUE TITLE
[Bug]: The lost of refresh token in Google OAuth

### ISSUE THREAD

**Issue by figwood** [lowcoder-org/lowcoder#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When login with Google account, it will return an access_token and an refresh_token, the access_token will be expired in about an hour, but the refresh_token will be valid all the time and it is used to get a new access_token, see [here](https://developers.google.com/identity/protocols/oauth2/web-server) . In lowcoder, both of them will be stored in DB, but the problem is that the refresh_token will only be returned in the first time user login, if users logout and re-login, it will return null in refresh_token and once it has been stored in DB, we will lose refresh_token.

Without refresh_token, the access_token can't be refreshed automatically, users have to re-login again every hour, which is quite annoying. 

It could be easily solved by adding these code in [updateConnection](https://github.com/lowcoder-org/lowcoder/blob/ffa595ab13af50aeddb18a57e746a51a5bcc31fd/server/api-service/lowcoder-server/src/main/java/org/lowcoder/api/authentication/service/AuthenticationApiServiceImpl.java#L240) function,  ,

```java
        //if auth by google, set refresh token
        if (authUser.getSource().equals(AuthSourceConstants.GOOGLE)) {
            authUser.getAuthToken().setRefreshToken(oldConnection.getAuthConnectionAuthToken().getRefreshToken());
        }
```

 but it's too ugly, hope there could be any better solutions.

### Expected Behavior

Users don't have to re-login every hour after login with Google account.

### Steps to reproduce

1. login with Google account
2. logout
3. re-login with same Google account
4. wait an hour, refresh the page, it will redirect to login form

**Comment by FalkWolsky** [comment]
this should be solved with v2.4.4 - please re-open if this issue remains a problem for you! And thank you for your patience with us!
