### ISSUE TITLE
[Feat]: Auto-redirect unauthenticated users to Workspace auth URL for apps within that workspace

### ISSUE THREAD

**Issue by lanedsmu** [lowcoder-org/lowcoder#823]
Applications within a workspace may have multiple (different) authentication providers. When an unauthenticated user browses to an application, that user isn't redirected to the workspace Auth URL; instead, that user is redirected to authenticate at the main Lowcoder login page.

Instead, users should be redirected to the authentication screen for the workspace that holds the application.  
It would be even better if we were able to define a default provider (besides email), and they were redirected directly to that IdP, such that they never saw the email  login page.

I'm wondering if it might make sense to build in a check for authentication details within an app, and then redirected via javascript to the relevant IdP...that could be a reasonable workaround, and such a thing may even offer some significant benefits to the app creator.  I'm not at all sure if adding such a module or component option to an application might be easier than changing the global LowCoder platform, but I could envision that working well also, perhaps.

**Comment by lanedsmu** [comment]
Very much related: when browsing to an application and being redirected to authentication, the user should be redirected back to the originally-requested app, rather than to the main Lowcoder home page.

**Comment by FalkWolsky** [comment]
We are on it - but this is a bit bigger topic as it involves backend API change.

**Comment by raheeliftikhar5** [comment]
This is done in v2.4.1
