### ISSUE TITLE
[Feat]:  Allow for configuring base URL for Oauth redirect URL

### ISSUE THREAD

**Issue by lanedsmu** [lowcoder-org/lowcoder#824]
The redirect URL sent to an Oauth IdP like Keycloak appears to be hard-coded using the default SSL port of 443.  
For those running a true out-of-the-box Docker deployment, or for those testing LowCoder on a system with multiple web sites, 443 may not be an option for hosting Lowcoder, in which case the redirect URL sent to the Oauth provider will fail.

If it were possible configure--either through environment variable or Docker-compose.yaml entries--a base URL that was used to construct URLs like the Oauth redirect URL, that would allow users to run Lowcoder on nonstandard SSL ports.

**Comment by FalkWolsky** [comment]
Hmm. We cannot confirm that this would be hard-wired in the code.
We will test it and come back

**Comment by FalkWolsky** [comment]
We added this in v2.4.0 with the Generic OAUTH Provider Config. Thank you for your patience!
