### ISSUE TITLE
[Bug]: Table Page Size options hidden by fixed table headers

### ISSUE THREAD

**Issue by lanedsmu** [lowcoder-org/lowcoder#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When "fixed table headers" is select in a table, and the toolbar is pinned to the top of a table, the page size drop down is hidden by the header row:
<img width="143" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/80843079/d30b9ba9-8f3d-4b72-8e43-efc10676ffdc">

This is exaccerbated by unchecking "Fixed Toolbar", which when turned off with a top toolbar and fixed headers mostly doesn't appear at all:
<img width="258" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/80843079/8072bbba-4991-47d2-ba33-2fe898faa296">

When "Fixed headers" is turned off *AND* "fixed toolbar is on", or if the toolbar is at the bottom of the table, the page size behaves as expected:
<img width="134" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/80843079/cc3255c7-3896-4481-8ed7-0392ebc437b9">

### Expected Behavior

Page size dropdown should appear over all other text on the screen when it is selected

### Steps to reproduce

Pin table toolbar to the top of the table, and uncheck "fixed toolbar".
Pin table toolbar to the top of the table and check "fixed headers".  

### Environment

Single-container docker image, v2.3.1, on Enterprise Linux

**Comment by FalkWolsky** [comment]
We solved this in v2.4.0. Thank you for your patience and to report it here!
