### ISSUE TITLE
[Bug]: The website not working while deploying via docker locally.

### ISSUE THREAD

**Issue by tiodot** [lowcoder-org/lowcoder#855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are some js errors,  and the login page is empty
![image](https://github.com/lowcoder-org/lowcoder/assets/5645617/d9493d74-ab46-4c1d-9c5a-739c1d382dca)

### Expected Behavior

The page will work properly while deploying locally

### Steps to reproduce

Just take the step of the [document](https://docs.lowcoder.cloud/lowcoder-documentation/setup-and-run/self-hosting)

### Additional Information

The mainly because the language is "de", but I don't find this snippet code in the source code.
![image](https://github.com/lowcoder-org/lowcoder/assets/5645617/fc8f3d04-2bb3-4274-bd1f-c7e5ee17e019)

It works right while I build the fronted code locally.

**Comment by FalkWolsky** [comment]
This is solved already and was only in the /latest docker image tag. We will publish in the next hours a new version (a preview to 2.4) as /latest tag - by which this effect disappear.
Normally it is suggested to use a version tag - and the latest stable one was v2.3.1
