### ISSUE TITLE
[Bug]: Table current row values is not passed correctly to module input nested in expanded view

### ISSUE THREAD

**Issue by vasileermicioi** [lowcoder-org/lowcoder#863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems like values to module are propagated from selectedRow instead of the currentRow, but for the text in the expandable view works fine (also using currentRow)
![image](https://github.com/lowcoder-org/lowcoder/assets/45198547/f210b965-b199-492f-9156-de3c72ae2ab5)

### Expected Behavior

Module from expandableView to pick values from currentRow, not from selectedRow

### Steps to reproduce

1) Create a module with a input
2) Create an app with a table
3) Activate expandableView option
4) Drag a text and the module in the expandable view
5) Set text and module input to {{currentRow.code}} (or other field)
6) Expand a few rows (but don't change selection)

Result: the text is showing the value from currentRow, and the view from selectedRow

**Comment by FalkWolsky** [comment]
We solved this in v2.4.0
