### ISSUE TITLE
AGPL license needed for all plugins?

### ISSUE THREAD

**Issue by andrewschmidt-a** [lowcoder-org/lowcoder#889]
### Discussed in https://github.com/lowcoder-org/lowcoder/discussions/888

<div type='discussions-op-text'>

<sup>Originally posted by **andrewschmidt-a** May 16, 2024</sup>
I know that AGPL requires releasing the source code for all modifications to the source code. However if we develop plugins that is an extensibility scenario not modification.  do we also need to release source code? </div>

**Comment by FalkWolsky** [comment]
Plugins - delivered by their own repository are not bound to the AGPL.
Would you place the Plugin Code inside the Lowcoder Repository - then they would get part of the AGPL by this.
Mind, that when you publish them via NPM for example, their minified code is public still.
But it can have it's own license.
