### ISSUE TITLE
[Bug]: Table select option prefix icon does not working

### ISSUE THREAD

**Issue by devapplicationbuilder** [lowcoder-org/lowcoder#899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As you can see in the attached images, the prefix icon for the type selection column is not working. I also tested it on version 2.3.1 and it doesn't work there either.

If i make the column editable and then double click on column to change value is working... but i think this should also work in non editable columns and also in editable columns without focus on the cell.

See the pictures here:
[Pictures](https://imgur.com/a/XTEeuJZ)

### Expected Behavior

It should show the prefix icon in editable/non-editable grid columns without user interaction (focus on column).

### Steps to reproduce

1. Add a table
2. Set Select for a column type
3. Add Prefix icon to the column

### Environment

It happens on versions 2.3.1 and 2.4.0

**Comment by raheeliftikhar5** [comment]
@devapplicationbuilder Thank you for sharing. This is updated now and will be available in next release i.e. 2.4.1
