### ISSUE TITLE
[Bug] Move App to Folder is showing very large images only instead of folder names

### ISSUE THREAD

**Issue by yogeshvachhani** [lowcoder-org/lowcoder#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/0061a1d9-ea7b-4856-8bc9-bb43f6759514)

![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/d087b7c3-05ae-482b-8f3b-307dc2f34b3c)

### Expected Behavior

It should show names of folders

### Steps to reproduce

Select `Move to Folder` command from pop-up menu of an app.

![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/d4d74273-c1f0-4a1d-8dc5-e5a8390535e0)

**Comment by FalkWolsky** [comment]
Will be solved in v2.4.1. Thank you very much for reporting - and please excuse!
