### ISSUE TITLE
[Bug]: timeline component caches erroneous entries when "Newest Events First" toggle is on

### ISSUE THREAD

**Issue by James4L** [lowcoder-org/lowcoder#902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There's a strange caching issue with the timeline component. Basically the component display isn't completely refreshed when the source data changes. The last element seems to be cached. My usual tricks around this by having the component reading a state value and setting the state to NULL between reloads does not even clear the contents of the timeline component. 
Screenshots showing the issue. obj_timeLineData.value contains 0 items.
Timeline component has the data source from that object. Yet timeline shows cached entries. The more the source data changes the more out of wack the cached contents get.
This problem only occurs when the "Newest Events First" slider is toggled on. When it is off, the timeline display refreshes between data changes as you would expect. 

You can see below the component is still showing entries even when the source object has none:
![image](https://github.com/lowcoder-org/lowcoder/assets/53325425/5f7a7060-2df9-4ed5-bf49-9604db74b74d)
![image](https://github.com/lowcoder-org/lowcoder/assets/53325425/32ce5776-873b-4717-8f8c-59eda8b3c6b3)
![image](https://github.com/lowcoder-org/lowcoder/assets/53325425/6540490f-daeb-43aa-b55f-4e1a5d6079db)

Setting "Newest Events First" to False, the component behaves as you would expect.

### Expected Behavior

The timeline component should completely refresh its display when the source changes, regardless of the toggle.

### Steps to reproduce

Source data object: A temporary state object which is populated from a JS function to build an array of data (not sure if this part of the problem because the usual triggers around data query refresh aren't executed)

Toggle the "Newest Events First" slider on. Change the source data. The most recent event from the previous data remains in the component display along with the new data.

### Environment

Lowcoder cloud

**Comment by raheeliftikhar5** [comment]
@James4L which version of Lowcoder you are using?

**Comment by raheeliftikhar5** [comment]
This is fixed in v2.4.4

**Comment by sasch901** [comment]
Maybe this Error is back again in 2.6.5 @raheeliftikhar5
