### ISSUE TITLE
[Bug]: lowcoder.cloud speaks of "Fully Opensource with Self-Hosing possibility."

### ISSUE THREAD

**Issue by rmu75** [lowcoder-org/lowcoder#903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/lowcoder-org/lowcoder/assets/9028252/2c4ec8d5-16e8-41a3-a31d-6e16932f9002)

### Expected Behavior

Don't speak of self-hosing.

### Steps to reproduce

open https://lowcoder.cloud/ and scroll down

**Comment by FalkWolsky** [comment]
Could you please give us a hint of what you would like to express?
Where do you find it is a bug? What is related to Self-hosting a Bug in this context?
Eventually you were not aware about the docs? https://docs.lowcoder.cloud/lowcoder-documentation/setup-and-run/self-hosting

**Comment by rmu75** [comment]
Sorry, it is probably hard to see, but there is a (really funny) typo (hosing vs. hosting). Your bug template really doesn't have anything appropriate for that situation.

**Comment by FalkWolsky** [comment]
AHHHHH! Good one! We truly had overseen this. Now all makes sense and we are very thankful for your hint!

**Comment by FalkWolsky** [comment]
Done + 1000 times thank you!
