### ISSUE TITLE
"Invite Members" menu link interferes with other menu items

### ISSUE THREAD

**Issue by lanedsmu** [lowcoder-org/lowcoder#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Invite Members" link ont he left-hand side of the page interferes with the main menu options when the browser window is not tall enough to fit all of the menu items.  This makes it fiddly and difficult to select the menu item that shares space with the Invite Members link:
<img width="135" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/80843079/e8a04b11-e476-4335-88fe-540398f05fc1">

The invite members link scrolls with the page, so it's also not possible to scroll up or down to move the affected menu option out of the way:
<img width="125" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/80843079/6288c122-b4e7-4751-8db2-a3cde289f97f">

When the window is tall enough, all works quite well.  
This is the case both on Chromium and Firefox browsers, at least.

### Expected Behavior

The invite members link should be -- if not just another menu option -- below the left-hand menu at all times, regardless of the vertical sizing of the browser window.

### Steps to reproduce

Browse to a Lowcoder workspace home page; reduce the vertical size of the browser window.  Invite Members will stay pinned to the bottom-left, but it only will move when the window is resized.  Once the size is set, it'll scroll with the page content (menu).

### Environment

v2.4.0 Docker multi image on enterprise linux

**Comment by lanedsmu** [comment]
I'll add: since there's already a "invite members" button in the "all members" user group, perhaps this link isn't necessary at all?

**Comment by FalkWolsky** [comment]
In general, we need to work on the whole invite section. It should be possible to invite members via eMail for example... We agree that the button down there is not necessary. Same time, in many screen resolutions the button does not overlap. Only on smaller screens / browser windows. We would therefore not say it is a bug - but change it to enhancement.
