### ISSUE TITLE
[Feat]: Allow REST queries to use web proxy

### ISSUE THREAD

**Issue by lanedsmu** [lowcoder-org/lowcoder#922]
**Is your feature request related to a problem? Please describe.**
REST queries currently cannot use web proxy for outbound http(s) access, which means that installations that rely on outbound proxy for Internet access cannot use REST queries to remote endpoints.

**Describe the solution you'd like**
Allow REST queries to use a system web proxy

**Describe alternatives you've considered**
Direct firewall rules allowing outbound https traffic are an option, though many installations rely on proxies and don't have a lot of flexibility in firewall settings.

**Additional context**
A good solution would be just to set the container to use the docker http_proxy and https_proxy environment variables (also honoring no_proxy).  
A great solution woudl be to have this set on a query-by-query basis, where one either could specify the proxy to use in the query settings, or simply flag whether that query should use the system proxy settings.

**Comment by FalkWolsky** [comment]
This is available in 2.4.1 (currently already available at the /dev image tag)
