### ISSUE TITLE
[Feat]: api/applications/list - to add more fields

### ISSUE THREAD

**Issue by FalkWolsky** [lowcoder-org/lowcoder#923]
The following fields in the response need to be added:

- title
- description
- category
- icon
- published
- publishedVersion
- lastPublishedTime

**Comment by dragonpoo** [comment]
Could anyone explain about the meaning of these fields?
Where should I get them?
- icon
- published
- publishedVersion
- lastPublishedTime
Thanks

**Comment by adnanqaops** [comment]
This has been deployed in V2.5.3, so, closing out this ticket.
