### ISSUE TITLE
[Bug]: PASSWORD_RESET_EMAIL_TEMPLATE - not to publish on orgCommonSettings

### ISSUE THREAD

**Issue by FalkWolsky** [lowcoder-org/lowcoder#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PASSWORD_RESET_EMAIL_TEMPLATE will get published at api/applications/ API endpoints as part of orgCommonSettings. However, this information would only be needed in the backend.

### Expected Behavior

Not to publish it at the api/applications/ endpoints

### Steps to reproduce

Call GET /api/applications/<appID>/view as example

**Comment by ludomikula** [comment]
This is fixed, will be release as part of 2.4.1 version.
