### ISSUE TITLE
[Bug]: setValue() doesn't update value before calling then()

### ISSUE THREAD

**Issue by mat02** [lowcoder-org/lowcoder#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the setValue() method to update the value of a temporary state and chaining a subsequent function with then(), the updated value is not reflected in state1.value.

Screenshot:
![image](https://github.com/lowcoder-org/lowcoder/assets/1629659/1db4b0b5-3c09-4d00-869f-ad37001837ae)

Demo app (run query1 and observe console output):
[Demo App.json](https://github.com/user-attachments/files/15532917/Demo.App.json)

### Expected Behavior

The updated value should be present in state1.value after the setValue() method is called and the then() function is executed.

### Steps to reproduce

1. Call the setValue() method to update the temporary state's value.
2. Chain a function using then().
3. Attempt to access the updated value in state1.value.

### Environment

Selfhosted Lowcoder 2.3.1
Cloud Lowcoder 2.4.0

**Comment by mat02** [comment]
@raheeliftikhar5 Don't want to rush you, but did you have time to verify if this issue is reproducible using attached demo app? I just want to be sure that what I'm seeing is really a bug and not something on my side, because it really stalled my project.

**Comment by raheeliftikhar5** [comment]
@mat02 Yes this is valid issue and i am working on the fix.

**Comment by mat02** [comment]
@raheeliftikhar5 Ok, thank you very much. If I can be of any help, don't hesitate to ask :)

**Comment by adnanqaops** [comment]
As confirmed from Raheel, this issue was fixed. Done and Deployed to Prod. So, closing out this issue.
