### ISSUE TITLE
[Bug]: Column Layout Component - wrong rendering

### ISSUE THREAD

**Issue by FalkWolsky** [lowcoder-org/lowcoder#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Column Layout Component does not render the height of the columns in a row correctly.
Additionally, if nested, the display is disturbed further and the boundaries of columns are not to see (gap not displayed).
Also the react resizeable handlers and bounding lines are not displayed proper.

### Expected Behavior

The Display, also in nested configurations would be correct placed, gaps respected and the resizeable handlers are to see proper everywhere.

### Steps to reproduce

Drag the Column Layout Component to the canvas and drag a second Column Layout Component in a column of the first hand placed Column Layout Component (nesting)

**Comment by raheeliftikhar5** [comment]
This is fixed in 2.4.1
