### ISSUE TITLE
[Feat]: Use postgres instead of mongodb

### ISSUE THREAD

**Issue by rhuanbarreto** [lowcoder-org/lowcoder#946]
**Is your feature request related to a problem? Please describe.**

Is there a way to use a PostgreSQL DB instead of MongoDB? For self hosting, mongoDB has few options on the cloud. With Postgres we could use any cloud provider or specialized DB provider like Neon.

**Comment by placidic** [comment]
I would imagine not without forking off and majorly refactoring the entire backend.  It sounds like something similar to the pocketblocks project, which also like lowcoder was initially forked from open blocks, but swapped out the backend to use pocketbase.  The whole paradigm shift between rdbms and noSql is so vast, there's rairly a non resistant conversion path and usually requires complete rearchitecting

**Comment by rhuanbarreto** [comment]
I agree. But I also see this as a major barrier for businesses to implement it once cloud providers are not allowed to host mongodb databases as managed services. And monogdb cloud is not an easy option right away. But I totally understand the point of rearchitecting. Just that before (in openblocks) we decided to not push for it and went for Tooljet because of this. So maybe in this takeover you could consider this.

**Comment by FalkWolsky** [comment]
We must admit, that till now it was not a major barrier for businesses - as mongo is often used as Docker image.
Also next to Atlas, still various hosting providers offers MongoDB as Replicaset or Cluster. [placidic](https://github.com/placidic) is right - to change the backend DataBase is a truly big project. Naturally a change to Postgres sounds on firsthand charming - and believe us, we discussed this. However, this changes a lot of good paradigms that we can currently profit. So, not really in the near future.

However, somewhen (2025) we think to rework the backend. And then it may be an option.
