### ISSUE TITLE
[Feat]: Easily apply themes (like the look of retool) to components in one or two clicks 

### ISSUE THREAD

**Issue by swhitlow-gmtv** [lowcoder-org/lowcoder#951]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
I would like to easily apply themes (like the look of retool) to components in one or two clicks. When building out UI's it would be very nice if there was a way to "apply" standard looks and styles to all of the components at once for an already built app (or one you are about to build). Themes like "Bootstrap" theme or "Retool" style of components, or "Material" design or something similar would be really great to have as well as allow us to quickly transition from another tool we are working in.

**Describe alternatives you've considered**
Customizing every component I create (which is a painstaking process right now)

**Additional context**

**Comment by FalkWolsky** [comment]
Theming for colors was already in place. But it will be of joy to hear that we actually this week work exactly on this feature. We will release it latest with 2.4.2

**Comment by swhitlow-gmtv** [comment]
Awesome! Can’t wait for the release!

**Comment by adnanqaops** [comment]
This has been released, so closing out this ticket.
