### ISSUE TITLE
[Bug]: table with margin, border, fixed height, fixed header and toolbar without pagination

### ISSUE THREAD

**Issue by sbash78** [lowcoder-org/lowcoder#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In [table example] from [public marketplace] let see first table "A table with margin, border, fixed height, fixed header and toolbar. With conditional Row Color and Conditional Column Color. Also, the table features hierarchical data display.". 
This table without pagination and must scroll records inside fixed height area. 
But not work in new release.

### Expected Behavior

like as previous release table without pagination must scroll records inside fixed height area.

### Steps to reproduce

public demo example  [table example] from lowcoder [public marketplace]. first table "A table with margin, border, fixed height, fixed header and toolbar. With conditional Row Color and Conditional Column Color. Also, the table features hierarchical data display.".

**Comment by FalkWolsky** [comment]
As this one is pretty much reported recently too, we will close your ticket, in favor of the more recent duplicate.
https://github.com/lowcoder-org/lowcoder/issues/1051
