### ISSUE TITLE
[Bug]: Icon component does not show when set to Auto

### ISSUE THREAD

**Issue by yogeshvachhani** [lowcoder-org/lowcoder#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After adding Icon component to App when we set an icon it does not if the `Icon Autosize` is set to **Auto**.
![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/9e7eb829-bcf6-4b26-965f-927682bb4d7a)

But if we set `Icon Autosize` is set to **Fixed** is show.
![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/a3260b06-b0d7-4938-b234-9242124eebde)

### Expected Behavior

![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/eb8c0b55-1939-4047-9a98-66a2bb1d13a5)

### Steps to reproduce

After adding Icon component to App when we set an icon it does not if the `Icon Autosize` is set to **Auto**.
![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/9e7eb829-bcf6-4b26-965f-927682bb4d7a)

But if we set `Icon Autosize` is set to **Fixed** is show.
![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/a3260b06-b0d7-4938-b234-9242124eebde)

**Comment by raheeliftikhar5** [comment]
This is fixed in v2.4.4
