### ISSUE TITLE
[Bug]: hidden property, error not hide on autoHeight components

### ISSUE THREAD

**Issue by vietdanh1899** [lowcoder-org/lowcoder#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On version 2.4.1.
![image](https://github.com/lowcoder-org/lowcoder/assets/8018856/facdceaf-210f-4ce2-8b65-bfb28f9e73e3)
![image](https://github.com/lowcoder-org/lowcoder/assets/8018856/d659a719-a1c1-4b3e-b948-db3f7b2fb05b)
Components with autoHeight will have error that it is still show in preview/view despite having set hidden=true.

### Expected Behavior

Components which set hidden=true should not show in preview/view.

### Steps to reproduce

Set components autoHeight=true and hidden=true

**Comment by vietdanh1899** [comment]
Another issue mentioned this bug #963

**Comment by raheeliftikhar5** [comment]
@vietdanh1899 this is fixed and will be release with 2.4.2
