### ISSUE TITLE
[Bug]: "Cannot read property 'findIndex' of undefined" When putting a table in a listview

### ISSUE THREAD

**Issue by Howe829** [lowcoder-org/lowcoder#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1286" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/28386363/19abd16c-c57c-4492-9f51-f7741a84f255">
Just put a table in a listview then it will get an error

### Expected Behavior

 put a table in a listview 

### Steps to reproduce

 First,put a table in a listview and refresh the page or click the Preview button, then you will see the error

### Environment

Version: 2.4.0-2.4.0 #e06aa6d6

**Comment by adnanqaops** [comment]
This issue is not there anymore. I have checked on V.2.4.7. So, I am closing out this ticket.
Please, reopen this ticket if you found this issue again.
