### ISSUE TITLE
[Bug]: Divider component styling issues

### ISSUE THREAD

**Issue by adnangit1993** [lowcoder-org/lowcoder#977]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

There are mainly two issues with Divider : 

1. Divider Component loses it's default styling when a TEXT is added into it. 

**Divider without TEXT added**
![image](https://github.com/lowcoder-org/lowcoder/assets/171674758/1525e8dc-a872-44a6-a46c-7599528ca5de)

**Divider with TEXT added**
![image](https://github.com/lowcoder-org/lowcoder/assets/171674758/b440a52b-0e28-4632-8239-ecb3cc192989)

2.  Divider Component has now some default border-radius, due to which the ends of the Divider curve down slightly and that looks awkward.
![image](https://github.com/lowcoder-org/lowcoder/assets/171674758/1525e8dc-a872-44a6-a46c-7599528ca5de)

### Expected Behavior

1. Divider Component should behave same whether a TEXT is added or not
2. Remove default value for border-radius for divider

### Steps to reproduce

Mentioned issues can be easily reproduced by dragging the Divider Component on the Canvas and adding some TEXT to it.

**Comment by FalkWolsky** [comment]
This was solved in v2.4.3
