### ISSUE TITLE
[Bug]: Column width adjust changes sort

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the setting "Column width adjusted by user" is set, it's not possible to adjust the width without sorting the table by that column.

### Expected Behavior

Don't sort the table.

### Steps to reproduce

- Set setting.
- Publish.
- Adjust wdith.

**Comment by FalkWolsky** [comment]
No, in v2.4.1 we cannot prove this behaviour. It seems to behave as expected.
If you find this behaviour in v2.4.1, please make a video and re-open the issue, so we can understand eventual special circumstances

**Comment by renekahr** [comment]
Here is a screen recording.

https://github.com/lowcoder-org/lowcoder/assets/100137712/f84481ce-5af2-4156-bca5-c07b7ace09e1
