### ISSUE TITLE
[Bug]: Table column setting "Mouseover" doesn't work

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting the text overflow setting to "Mouseover", it still wraps the content.

### Expected Behavior

Don't wrap the content.

### Steps to reproduce

- Set the column to mouseover
- See the result

**Comment by FalkWolsky** [comment]
Thank you for reporting! We will work on it as soon as possible!

**Comment by FalkWolsky** [comment]
It is solved in v2.4.2
