### ISSUE TITLE
[Feat]: Default Homepage setting doesn't work

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting a specific app as **Default Homepage** in the workspace settings, the user (Member) is being redirected to some weird page where the selected app is embedded instead of being redirected to the app itself.

### Expected Behavior

Route the user to the /view endpoint of the selected app.

### Steps to reproduce

- Set the setting
- Log in as a member

**Comment by FalkWolsky** [comment]
Since version 2.4.1, we have a redirect mechanism "back to the app" after login, which the user did try to open.
You can make use of this and publish a public app and advice users to open this.
Out of the /root path - currently there is no fast hotfix

**Comment by renekahr** [comment]
@FalkWolsky This is not really what I'm trying to achieve. It used to work before. Why did it change?

**Comment by renekahr** [comment]
I don't see any reason for sending the user to some kind of backend route where the user can see a marketplace, settings and all that stuff. All our users have no idea about Lowcoder and what it does. They should focus on using the app(s) build within Lowcoder to solve their problems and achieve their goals.

**Comment by FalkWolsky** [comment]
We fully understand your view. We have to separate:
- Members (any logged in Lowcoder User)
- Editors & Admins

It truly depends. In Large companies you may have the scenario, where a team (Editors) does like it as it is now - as home page of a Workspace (a Org).

However, if you have the "End-User" in mind (that not even need to see that the Apps are build with Lowcoder) - and surely will not use the Editor - then a direct pass-through after the login is good.

However, now we are already at a conventional challenge: If you have a muti-workspace setup and users use the main login path /user/auth/login - then it is ambiguous to which workspace and which initial app we should route.

So, you would solve this problem in offering a workspace-individual login URL like: https://app.lowcoder.cloud/org/645...fb9/auth/login

So, this is not much different from an App /view URL as "entry point" of the user-jouney.

When you have an App that is the entry point, users will end up at this app again after the login. Therefore we think it is quite comparable.

Only different scenario: You have a single Workspace Setup (ENTERPRISE_MODE).
Then obviously there is no ambiguity.

However, what we will take with us as "to do" is the following: 

- IF Members (any logged in Lowcoder User) -> the. route to the initial app directly
- IF Editors & Admins (route like it is done currently)

Agree?

**Comment by BobLouderback** [comment]
I'd also like to see this feature sooner than later.  End users (outside of our org) will be confused when they see Marketplace, Settings, Your Apps, etc.

**Comment by renekahr** [comment]
> However, what we will take with us as "to do" is the following:
> 
> * IF Members (any logged in Lowcoder User) -> the. route to the initial app directly
> * IF Editors & Admins (route like it is done currently)
> 
> Agree?

@FalkWolsky I do understand the different scenarios. But yes, as you said. This would be a good solution.

**Comment by FalkWolsky** [comment]
We did solve it now with v2.4.2 / v2.4.3. Hope that it works now good for all cases?
Gladly re-open the issue if there is still "an issue" with this behavior.
