### ISSUE TITLE
[Bug]: Adding a File Upload and a Json Schema Form creates additional JSON Schema property on both controls

### ISSUE THREAD

**Issue by Banbury** [lowcoder-org/lowcoder#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is an odd one:
 * Insert a Json Schema Form
 * Insert a File Upload
 * Select first one and then the other component
 * The File Upload has now a JSON Schema property
 * Json Schema Form has now two of them
 * Deleting the Json Schema Form will remove the property from the File Upload

### Expected Behavior

No additional properties should be added.

### Steps to reproduce

See "Current Behavior"

### Environment

Version: 2.4.1-2.4.1 #fdffe017
Environment: Docker

**Comment by FalkWolsky** [comment]
Oha! That is indeed weird. But i'm sure we will find the reason and can fix this.

**Comment by raheeliftikhar5** [comment]
This is fixed in v2.4.4
