### ISSUE TITLE
[Bug]: Hide property of text component doesn't work

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting the `hide` property from the **Text Display** to `true`, it doesn't do anything.

### Expected Behavior

Hide the component.

### Steps to reproduce

1. Add a Text Display
2. Set the hide prop to true
3. Look it up in the /view route

**Comment by FalkWolsky** [comment]
We kindly excuse this "glitch". It was a silly bug, that affected a number of components.
It was solved in v2.4.2
