### ISSUE TITLE
[Bug]: Tabbed Container has some duplicate styling properties

### ISSUE THREAD

**Issue by adnanqaops** [lowcoder-org/lowcoder#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For Tabbed Container component, **Border-width** and **Border-style** properties are twice shown.
Relevant Discord thread : [**Border-width** and **Border-style** properties are twice shown.](https://discord.com/channels/1096896040159957084/1121839720759046286/threads/1255509447938412656)

### Expected Behavior

Show **Border-width** and **Border-style** properties only once in the properties window.

### Steps to reproduce

1. Drag a Tabbed Container component on to Canvas.
2. Try changing **Border-width** and **Border-style** properties.
3. You can reproduce this issue by exploring this app here : https://app.lowcoder.cloud/apps/667c1499f0558f2f43e37a48/edit

**Comment by FalkWolsky** [comment]
This was solved already
