### ISSUE TITLE
[Bug]: Hide property on form button doesn't work

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hide property on form button doesn't work

### Expected Behavior

Hide the form button when set to `true`.

### Steps to reproduce

- Add form button
- set hide to true
- check it out in the /view route

**Comment by Just1nWang** [comment]
I also encountered this problem. 
The hide attribute of the component can work normally on the editing and preview pages, but when using lowcoder-sdk to render the page, the hide attribute cannot take effect and the component is not hidden.

**Comment by FalkWolsky** [comment]
We have fixed this and will publish the new SDK already with this fix in the nearest day.
Also, we think to have v2.4.2 ready by the next weekend, so this bug will disappear by this.
Please excuse it appeared at all!
