### ISSUE TITLE
[Bug]: Select Children text is white on default

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The text of the options in a select field is white on default. They are basically not readable.
<img width="299" alt="image" src="https://github.com/lowcoder-org/lowcoder/assets/100137712/a0342b38-96a4-49cb-a28e-f758c9ff46bd">

### Expected Behavior

Black on default

### Steps to reproduce

- add select field
- publish
- check out in the /view route

**Comment by FalkWolsky** [comment]
It is solved in v2.4.2
